import type { Mission, Screen } from '../types'
import { BRAND } from '../brand'

/**
 * Mission 02 — James Bond / European Portuguese.
 * Build copy from the compound-learning critical-test spec v0.2, §7 and §10.
 *
 * Two things here differ deliberately from the source document, both to keep a
 * falsification criterion measurable rather than decorative:
 *
 *  1. The cold recall runs six items, not four. §12 defines reinforcement gain as
 *     the change for COMIGO, PODES, QUANDO and CLARO against their cold recall —
 *     but the spec's B02–B05 never measure CLARO, and measure no un-reinforced
 *     block at all. B04A (PERDI, control) and B05A (CLARO) close both gaps, giving
 *     a four-reinforced versus two-control comparison.
 *
 *  2. The crossover builds sentences that were never shown as a line. In the source
 *     document C03, C04, C06 and C09 repeat constructions taught three to five
 *     minutes earlier, which would let the headline cross-world transfer score be
 *     satisfied by short-term recall. Every block and structure is unchanged; only
 *     the nouns and pairings are new.
 */
export const SCREENS: Screen[] = [
  // ------------------------------------------------------------------ RETURN
  {
    id: 'B01',
    name: 'Welcome back',
    stage: 'RETURN',
    timecode: '00:00–00:08',
    purpose: 'Set up delayed recall without reminding the learner of any Top Gun answer.',
    type: 'briefing',
    eyebrow: BRAND.name + ' · MISSION 02',
    headline: 'What survived?',
    sub: 'Before we give you anything new, one question.',
    cta: 'FIND OUT',
    capture: ['mission02_start', 'previous_session_age_hours'],
  },
  {
    id: 'B02',
    name: 'Cold recall — COMIGO',
    stage: 'RETURN',
    timecode: '00:08–00:16',
    purpose: 'Test retained meaning before any cultural cue or film language appears.',
    type: 'meaning-check',
    target: 'comigo',
    role: 'reinforced',
    eyebrow: 'NO FILM. NO CLUES.',
    sub: 'Just Portuguese.',
    block: 'COMIGO',
    lead: 'means…',
    options: [
      { id: 'with_me', label: 'WITH ME', correct: true },
      { id: 'tomorrow', label: 'TOMORROW' },
      { id: 'i_need', label: 'I NEED' },
    ],
    wrong: 'Not time. Not need. Think about the relationship between two people.',
    hint: '“Come ___ me.”',
    reveal: 'COMIGO = with me.',
  },
  {
    id: 'B03',
    name: 'Cold recall — PODES',
    stage: 'RETURN',
    timecode: '00:16–00:24',
    purpose: 'Retrieve the request/ability hinge.',
    type: 'meaning-check',
    target: 'podes',
    role: 'reinforced',
    block: 'PODES…',
    lead: 'is the start of…',
    options: [
      { id: 'can_you', label: 'CAN YOU', correct: true },
      { id: 'i_lost', label: 'I LOST' },
      { id: 'where_is', label: 'WHERE IS' },
    ],
    wrong: 'This one opens a request.',
    hint: '“___ repeat?”',
    reveal: 'PODES… = you can / can you…',
  },
  {
    id: 'B04',
    name: 'Cold recall — PRECISO DE',
    stage: 'RETURN',
    timecode: '00:24–00:32',
    purpose:
      'Test durable retrieval of a Top Gun block that is combined rather than reinforced.',
    type: 'meaning-check',
    target: 'preciso_de',
    role: 'combined',
    block: 'PRECISO DE…',
    lead: 'means…',
    options: [
      { id: 'i_need', label: 'I NEED', correct: true },
      { id: 'i_cant', label: 'I CAN’T' },
      { id: 'not_going', label: 'I’M NOT GOING TO' },
    ],
    wrong: 'Need, ability and intention are different engines.',
    hint: 'Think: water. taxi.',
    reveal: 'PRECISO DE… = I need…',
  },
  {
    id: 'B04A',
    name: 'Cold recall — PERDI (control)',
    stage: 'RETURN',
    timecode: '00:32–00:40',
    purpose:
      'Baseline for a block Bond never touches. Without it, "no easier than comparable non-reinforced blocks" cannot be tested.',
    type: 'meaning-check',
    target: 'perdi',
    role: 'control',
    block: 'PERDI…',
    lead: 'means…',
    options: [
      { id: 'i_lost', label: 'I LOST', correct: true },
      { id: 'i_left', label: 'I’M LEAVING' },
      { id: 'i_forgot', label: 'OF COURSE' },
    ],
    wrong: 'This one is about something that is gone.',
    hint: 'Think: keys. ticket.',
    reveal: 'PERDI… = I lost…',
  },
  {
    id: 'B05',
    name: 'Cold recall — QUANDO',
    stage: 'RETURN',
    timecode: '00:40–00:48',
    purpose: 'Retrieve a hinge word that AMANHÃ will later strengthen.',
    type: 'meaning-check',
    target: 'quando',
    role: 'reinforced',
    block: 'QUANDO',
    lead: 'means…',
    options: [
      { id: 'when', label: 'WHEN', correct: true },
      { id: 'where', label: 'WHERE' },
      { id: 'why', label: 'WHY' },
    ],
    wrong: 'This one is about time.',
    hint: '“___ are we going?”',
    reveal: 'QUANDO = when.',
  },
  {
    id: 'B05A',
    name: 'Cold recall — CLARO',
    stage: 'RETURN',
    timecode: '00:48–00:56',
    purpose:
      'Baseline for the fourth reinforced block. §12 asks for its reinforcement gain but the source spec never measured it before Bond.',
    type: 'meaning-check',
    target: 'claro',
    role: 'reinforced',
    block: 'CLARO',
    lead: 'means…',
    options: [
      { id: 'of_course', label: 'OF COURSE', correct: true },
      { id: 'why_not', label: 'WHY NOT' },
      { id: 'not_yet', label: 'NOT YET' },
    ],
    wrong: 'This one is certainty, not a question.',
    hint: 'You say it when you agree without hesitating.',
    reveal: 'CLARO = of course.',
  },
  {
    id: 'B06',
    name: 'Retention result',
    stage: 'RETURN',
    timecode: '00:56–01:02',
    purpose: 'Make forgetting acceptable while establishing a baseline.',
    type: 'retention-result',
    eyebrow: 'WHAT SURVIVED',
    sub: 'Good. Now we add another world.',
    cta: 'CONTINUE',
    lowScoreCopy:
      'Some survived. Some need another encounter. That is exactly what reinforcement is for.',
    capture: ['cold_recall_score'],
  },

  // ---------------------------------------------------------------- AFFINITY
  {
    id: 'B07',
    name: 'Culture categories',
    stage: 'AFFINITY',
    timecode: '01:02–01:15',
    purpose: 'Capture category preference before Bond is presented as the next world.',
    type: 'culture-categories',
    headline: 'What do you know by heart?',
    sub: 'Choose up to three worlds you already carry around in your head. Not what sounds impressive. What you could quote, hum, recognise or argue about half-asleep.',
    max: 3,
    cards: [
      { id: 'film', title: 'FILM', examples: 'films, franchises, directors' },
      { id: 'tv', title: 'TV', examples: 'series, sitcoms, reality, drama' },
      { id: 'music', title: 'MUSIC', examples: 'artists, albums, songs' },
      { id: 'sport', title: 'SPORT', examples: 'teams, players, commentary' },
      { id: 'books', title: 'BOOKS', examples: 'novels, poetry, characters' },
      { id: 'comedy', title: 'COMEDY', examples: 'stand-up, sketches, panel shows' },
      { id: 'games', title: 'GAMES', examples: 'games, characters, worlds' },
      { id: 'other', title: 'OTHER', examples: 'something else entirely' },
    ],
    cta: 'NEXT',
  },
  {
    id: 'B08',
    name: 'Unaided favourite',
    stage: 'AFFINITY',
    timecode: '01:15–01:25',
    purpose: 'Get a property, artist or team the product did not suggest.',
    type: 'free-text',
    headline: 'Name one thing you know ridiculously well.',
    sub: 'A film. A series. An artist. A team. A book. Anything.',
    placeholder: 'Type it here',
    field: 'culture_free_text',
    cta: 'THAT ONE',
  },
  {
    id: 'B09',
    name: 'Forced next-world choice',
    stage: 'AFFINITY',
    timecode: '01:25–01:35',
    purpose: 'Measure demand among plausible worlds before advertising one.',
    type: 'forced-choice',
    headline: 'If these were all live tomorrow, which would you actually choose?',
    sub: 'Pick one.',
    cards: [
      { id: 'james_bond', title: 'JAMES BOND' },
      { id: 'friends', title: 'FRIENDS' },
      { id: 'harry_potter', title: 'HARRY POTTER' },
      { id: 'the_office', title: 'THE OFFICE' },
      { id: 'football', title: 'FOOTBALL' },
      { id: 'music', title: 'MUSIC I KNOW BY HEART' },
    ],
    escapeHatch: { id: 'something_else', title: 'SOMETHING ELSE' },
    field: 'next_world_pre',
    cta: 'CONTINUE',
  },
  {
    id: 'B10',
    name: 'Bond familiarity',
    stage: 'AFFINITY',
    timecode: '01:35–01:45',
    purpose: 'Treat cultural familiarity as an explicit covariate.',
    type: 'scale',
    eyebrow: 'ONE LAST THING.',
    headline: 'How well do you know James Bond?',
    points: [
      { value: 1, label: 'NEVER SEEN ONE' },
      { value: 2, label: 'A LITTLE' },
      { value: 3, label: 'SEEN A FEW' },
      { value: 4, label: 'KNOW IT WELL' },
      { value: 5, label: 'RIDICULOUSLY WELL' },
    ],
    field: 'bond_familiarity',
    cta: 'CONTINUE',
    skipInNeutral: true,
  },

  // ---------------------------------------------------------------- BRIEFING
  {
    id: 'B11',
    name: 'Mission briefing',
    stage: 'BRIEFING',
    timecode: '01:45–01:55',
    purpose: 'Explain that Bond adds to, rather than replaces, Top Gun.',
    type: 'briefing',
    eyebrow: 'MISSION 02 · JAMES BOND',
    headline: 'Six new pieces. Four old ones get stronger.',
    sub: 'The goal is not Bond Portuguese. The goal is more Portuguese.',
    cta: 'BEGIN',
    neutral: {
      eyebrow: 'MISSION 02',
      headline: 'Six new pieces. Four old ones get stronger.',
      sub: 'The goal is more Portuguese.',
    },
    capture: ['bond_begin'],
  },

  // ----------------------------------------------------------------- CONTACT
  {
    id: 'B12',
    name: 'Hook 01 — CHAMO-ME',
    stage: 'CONTACT',
    timecode: '01:55–02:07',
    purpose: 'Use the famous introduction as a memory hook for a real introduction.',
    type: 'block-intro',
    hook: 'BOND. JAMES BOND.',
    sub: 'The useful Portuguese hiding inside the ritual is:',
    phrase: { pt: 'Chamo-me James Bond.' },
    blocks: [{ id: 'chamo_me', pt: 'chamo-me…', gloss: 'my name is…' }],
    tapPrompt: 'Tap CHAMO-ME to hear it.',
    cta: 'CONTINUE',
    reveal: 'CHAMO-ME… = my name is…',
    introduces: 'chamo_me',
    neutral: {
      hook: undefined,
      context: 'You meet someone new. Say your name.',
      sub: 'The Portuguese you need is:',
    },
    capture: ['target_encounter'],
  },
  {
    id: 'B13',
    name: 'Build CHAMO-ME',
    stage: 'CONTACT',
    timecode: '02:07–02:19',
    purpose: 'Move immediately from the hook to the learner’s own identity.',
    type: 'tiles',
    context: 'Now make it yours.',
    headline: 'My name is Ana.',
    tiles: [
      { id: 'chamo_me', text: 'Chamo-me' },
      { id: 'ana', text: 'Ana' },
      { id: 'sou', text: 'Sou', distractor: true },
    ],
    answer: ['chamo_me', 'ana'],
    rules: [
      { when: 'uses', tile: 'sou', message: 'Sou = I am. The block you want is the whole CHAMO-ME.' },
      { when: 'not-first', tile: 'chamo_me', message: 'Start with the whole block: Chamo-me…' },
    ],
    reveal: 'Chamo-me Ana. One film hook. One real introduction.',
    acquires: 'chamo_me',
  },
  {
    id: 'B14',
    name: 'Escape Bond — CHAMO-ME',
    stage: 'CONTACT',
    timecode: '02:19–02:30',
    purpose: 'Confirm transfer with no Bond language present.',
    type: 'choice',
    context: 'You meet someone in Lisbon.',
    headline: 'My name is Miguel.',
    options: [
      { id: 'chamo_me', pt: 'Chamo-me Miguel.', correct: true },
      { id: 'preciso', pt: 'Preciso de Miguel.', feedback: 'That says you need Miguel. Only one answer introduces a name.' },
      { id: 'podes', pt: 'Podes Miguel.', feedback: 'Podes opens a request, not an introduction.' },
    ],
    reveal: 'Exactly. Bond has already disappeared.',
    chipHint: 'chamo_me',
  },
  {
    id: 'B15',
    name: 'Hook 02 — QUERIA',
    stage: 'CONTACT',
    timecode: '02:30–02:42',
    purpose: 'Use the drink-order ritual to introduce a high-value polite request.',
    type: 'block-intro',
    eyebrow: 'BOND ORDERS. YOU ORDER.',
    phrase: { pt: 'Queria um café.' },
    blocks: [{ id: 'queria', pt: 'queria…', gloss: 'I’d like…' }],
    tapPrompt: 'Tap QUERIA to hear it.',
    cta: 'CONTINUE',
    reveal:
      'QUERIA… = I’d like… In Portugal this is a very natural, polite way to ask for something.',
    introduces: 'queria',
    neutral: {
      eyebrow: 'AT THE COUNTER.',
      context: 'You want to ask politely.',
    },
    capture: ['target_encounter'],
  },
  {
    id: 'B16',
    name: 'Build QUERIA',
    stage: 'CONTACT',
    timecode: '02:42–02:54',
    purpose: 'Keep the request block intact while changing the noun.',
    type: 'choice',
    headline: 'I’d like water.',
    note: 'água = water',
    options: [
      { id: 'queria_agua', pt: 'Queria água.', correct: true },
      { id: 'quero_de_agua', pt: 'Quero de água.', feedback: 'Keep QUERIA whole. Then add what you want.' },
      { id: 'podes_agua', pt: 'Podes água.', feedback: 'Podes asks another person to do something. This is what you want.' },
    ],
    reveal: 'Queria água.',
    acquires: 'queria',
  },
  {
    id: 'B17',
    name: 'Escape Bond — QUERIA',
    stage: 'CONTACT',
    timecode: '02:54–03:06',
    purpose: 'Use the block in a normal café rather than a spy fantasy.',
    type: 'tiles',
    context: 'A café in Porto.',
    headline: 'I’d like a coffee.',
    note: 'um café = a coffee',
    tiles: [
      { id: 'queria', text: 'Queria' },
      { id: 'um_cafe', text: 'um café' },
    ],
    answer: ['queria', 'um_cafe'],
    rules: [{ when: 'order', message: 'QUERIA comes first.' }],
    reveal: 'Queria um café. This is useful today.',
    chipHint: 'queria',
  },

  // --------------------------------------------------------------- FIELDWORK
  {
    id: 'B18',
    name: 'Hook 03 — POSSO',
    stage: 'FIELDWORK',
    timecode: '03:06–03:19',
    purpose: 'Map the idea of licence to a simple Portuguese permission switch.',
    type: 'block-intro',
    eyebrow: 'LICENCE = PERMISSION.',
    sub: 'Portuguese gives you a permission switch:',
    blocks: [{ id: 'posso', pt: 'posso…?', gloss: 'can I / may I…?' }],
    tapPrompt: 'Tap POSSO to hear it.',
    cta: 'CONTINUE',
    reveal: 'POSSO…? = can I…? / may I…?',
    introduces: 'posso',
    neutral: {
      eyebrow: 'YOU NEED PERMISSION.',
      sub: 'Portuguese gives you a permission switch:',
    },
    capture: ['target_encounter'],
  },
  {
    id: 'B19',
    name: 'The first compound moment',
    stage: 'FIELDWORK',
    timecode: '03:19–03:33',
    purpose: 'Contrast new POSSO with existing PODES and make prior learning visibly useful.',
    type: 'match',
    eyebrow: 'YOU ALREADY OWN ONE HALF OF THIS.',
    pairs: [
      { blockId: 'podes', pt: 'Podes…?', en: 'Can YOU…?' },
      { blockId: 'posso', pt: 'Posso…?', en: 'Can I…?' },
    ],
    swapFeedback: 'Look at the person doing the asking: YOU or I. PODES = you. POSSO = I.',
    reveal: 'One new word just doubled what you can ask.',
    reinforces: 'podes',
  },
  {
    id: 'B20',
    name: 'Use POSSO',
    stage: 'FIELDWORK',
    timecode: '03:33–03:45',
    purpose: 'Put permission into an immediately useful phrase.',
    type: 'tiles',
    context: 'At a restaurant.',
    headline: 'Can I pay?',
    note: 'pagar = to pay',
    tiles: [
      { id: 'posso', text: 'Posso' },
      { id: 'pagar', text: 'pagar' },
      { id: 'q', text: '?' },
      { id: 'podes', text: 'Podes', distractor: true },
    ],
    answer: ['posso', 'pagar', 'q'],
    rules: [
      { when: 'uses', tile: 'podes', message: 'Podes asks whether the other person can. You are asking about yourself.' },
      { when: 'not-first', tile: 'posso', message: 'Start with the permission switch.' },
    ],
    reveal: 'Posso pagar? Another sentence that survives Bond.',
    acquires: 'posso',
  },
  {
    id: 'B21',
    name: 'Hook 04 — ONDE FICA',
    stage: 'FIELDWORK',
    timecode: '03:45–03:57',
    purpose: 'Introduce a location block through the universal mission/location problem.',
    type: 'block-intro',
    eyebrow: 'EVERY MISSION EVENTUALLY BECOMES A LOCATION PROBLEM.',
    blocks: [{ id: 'onde_fica', pt: 'onde fica…?', gloss: 'where is…?' }],
    tapPrompt: 'Tap ONDE FICA to hear it.',
    cta: 'CONTINUE',
    reveal: 'ONDE FICA…? = where is…? Use it for places.',
    introduces: 'onde_fica',
    neutral: { eyebrow: 'YOU NEED DIRECTIONS.' },
    capture: ['target_encounter'],
  },
  {
    id: 'B22',
    name: 'Build ONDE FICA',
    stage: 'FIELDWORK',
    timecode: '03:57–04:09',
    purpose: 'Apply the block to a common travel location.',
    type: 'tiles',
    headline: 'Where is the station?',
    note: 'a estação = the station',
    tiles: [
      { id: 'onde_fica', text: 'Onde fica' },
      { id: 'a_estacao', text: 'a estação' },
      { id: 'q', text: '?' },
    ],
    answer: ['onde_fica', 'a_estacao', 'q'],
    rules: [{ when: 'order', message: 'Keep ONDE FICA together, at the front.' }],
    reveal: 'Onde fica a estação?',
    acquires: 'onde_fica',
  },
  {
    id: 'B23',
    name: 'Smash old + new',
    stage: 'FIELDWORK',
    timecode: '04:09–04:25',
    purpose: 'Combine Top Gun PRECISO DE with Bond ONDE FICA in one practical situation.',
    type: 'composite',
    context: 'You need a taxi. Then you need to find the taxi rank.',
    headline: 'Build both.',
    parts: [
      {
        kind: 'tiles',
        id: 'need',
        prompt: 'I need a taxi.',
        tiles: [
          { id: 'preciso', text: 'Preciso' },
          { id: 'de', text: 'de' },
          { id: 'um_taxi', text: 'um táxi' },
        ],
        answer: ['preciso', 'de', 'um_taxi'],
        hint1: 'Old block first: Preciso de…',
        chipHint: 'preciso_de',
      },
      {
        kind: 'tiles',
        id: 'where',
        prompt: 'Where is the taxi rank?',
        note: 'a praça de táxis = the taxi rank',
        tiles: [
          { id: 'onde_fica', text: 'Onde fica' },
          { id: 'a_praca', text: 'a praça de táxis' },
          { id: 'q', text: '?' },
        ],
        answer: ['onde_fica', 'a_praca', 'q'],
        hint1: 'New block second: Onde fica…?',
        chipHint: 'onde_fica',
      },
    ],
    reveal: 'Two films. One ordinary problem.',
    combines: ['preciso_de', 'onde_fica'],
  },
  {
    id: 'B24',
    name: 'Hook 05 — AMANHÃ',
    stage: 'FIELDWORK',
    timecode: '04:25–04:37',
    purpose: 'Use a title as a highly compact time-word hook.',
    type: 'block-intro',
    hook: 'TOMORROW NEVER DIES.',
    sub: 'We only need one word from it:',
    blocks: [{ id: 'amanha', pt: 'amanhã', gloss: 'tomorrow' }],
    tapPrompt: 'Tap AMANHÃ to hear it.',
    cta: 'CONTINUE',
    reveal: 'AMANHÃ = tomorrow.',
    introduces: 'amanha',
    neutral: { hook: undefined, eyebrow: 'TOMORROW.', sub: 'One word:' },
    capture: ['target_encounter'],
  },
  {
    id: 'B25',
    name: 'QUANDO gets stronger',
    stage: 'FIELDWORK',
    timecode: '04:37–04:53',
    purpose: 'Combine the old time hinge with the new time answer.',
    type: 'composite',
    eyebrow: 'YOU ALREADY KNOW THIS ONE.',
    context: 'First, what does QUANDO mean? Then answer the question.',
    parts: [
      {
        kind: 'choice',
        id: 'meaning',
        prompt: 'QUANDO means…',
        english: true,
        options: [
          { id: 'when', pt: 'when', correct: true },
          { id: 'where', pt: 'where', feedback: 'QUANDO asks about time.' },
          { id: 'who', pt: 'who', feedback: 'QUANDO asks about time.' },
        ],
        chipHint: 'quando',
      },
      {
        kind: 'choice',
        id: 'answer',
        prompt: 'Quando vamos?',
        note: 'vamos = we’re going',
        options: [
          { id: 'amanha', pt: 'Amanhã.', correct: true },
          { id: 'claro', pt: 'Claro.', feedback: 'That agrees, but it does not give a time.' },
          { id: 'comigo', pt: 'Comigo.', feedback: 'QUANDO asks about time. AMANHÃ gives one time.' },
        ],
        chipHint: 'amanha',
      },
    ],
    reveal: 'Quando vamos? Amanhã. Old language just made new language easier.',
    reinforces: 'quando',
  },
  {
    id: 'B26',
    name: 'Escape Bond — AMANHÃ',
    stage: 'FIELDWORK',
    timecode: '04:53–05:05',
    purpose: 'Use tomorrow inside an old PODES request.',
    type: 'tiles',
    headline: 'Can you come tomorrow?',
    note: 'vir = to come',
    tiles: [
      { id: 'podes', text: 'Podes' },
      { id: 'vir', text: 'vir' },
      { id: 'amanha', text: 'amanhã' },
      { id: 'q', text: '?' },
    ],
    answer: ['podes', 'vir', 'amanha', 'q'],
    rules: [
      { when: 'not-first', tile: 'podes', message: 'You already know how PODES starts a request.' },
      { when: 'omits', tile: 'amanha', message: 'Add the new time word: amanhã.' },
    ],
    reveal: 'Podes vir amanhã? Three useful pieces working together.',
    acquires: 'amanha',
    combines: ['podes', 'amanha'],
  },

  // -------------------------------------------------------------- EXTRACTION
  {
    id: 'B27',
    name: 'Hook 06 — OUTRA VEZ',
    stage: 'EXTRACTION',
    timecode: '05:05–05:17',
    purpose: 'Use a title hook to teach a high-value repeat phrase.',
    type: 'block-intro',
    hook: 'NEVER SAY NEVER AGAIN.',
    sub: 'The useful piece for us is:',
    blocks: [{ id: 'outra_vez', pt: 'outra vez', gloss: 'again' }],
    tapPrompt: 'Tap OUTRA VEZ to hear it.',
    cta: 'CONTINUE',
    reveal: 'OUTRA VEZ = again.',
    introduces: 'outra_vez',
    neutral: { hook: undefined, eyebrow: 'AGAIN.', sub: 'One piece:' },
    capture: ['target_encounter'],
  },
  {
    id: 'B28',
    name: 'PODES + OUTRA VEZ',
    stage: 'EXTRACTION',
    timecode: '05:17–05:33',
    purpose: 'Create an obvious compound from an old request and a new repeat phrase.',
    type: 'tiles',
    headline: 'Can you say it again?',
    note: 'dizer = to say',
    tiles: [
      { id: 'podes', text: 'Podes' },
      { id: 'dizer', text: 'dizer' },
      { id: 'outra_vez', text: 'outra vez' },
      { id: 'q', text: '?' },
    ],
    answer: ['podes', 'dizer', 'outra_vez', 'q'],
    rules: [
      { when: 'not-first', tile: 'podes', message: 'Start with the request you already know.' },
    ],
    reveal: 'Podes dizer outra vez? This is what compounding should feel like.',
    combines: ['podes', 'outra_vez'],
  },
  {
    id: 'B29',
    name: 'Escape Bond — OUTRA VEZ',
    stage: 'EXTRACTION',
    timecode: '05:33–05:45',
    purpose: 'Reduce the phrase to a practical repair cue.',
    type: 'tiles',
    context: 'Someone speaks too fast.',
    headline: 'Again, please.',
    note: 'por favor = please',
    tiles: [
      { id: 'outra_vez', text: 'Outra vez,' },
      { id: 'por_favor', text: 'por favor' },
    ],
    answer: ['outra_vez', 'por_favor'],
    rules: [{ when: 'order', message: 'OUTRA VEZ is the whole “again” block. It leads.' }],
    reveal: 'Outra vez, por favor.',
    acquires: 'outra_vez',
    chipHint: 'outra_vez',
  },
  {
    id: 'B30',
    name: 'COMIGO returns',
    stage: 'EXTRACTION',
    timecode: '05:45–05:57',
    purpose: 'Reinforce a Top Gun block inside a different cultural world.',
    type: 'tiles',
    eyebrow: 'NO TEACHING THIS TIME.',
    headline: 'Come with me.',
    tiles: [
      { id: 'vem', text: 'Vem' },
      { id: 'comigo', text: 'comigo' },
    ],
    answer: ['vem', 'comigo'],
    hint1: 'You have seen this before. VEM + COMIGO.',
    reveal: 'Exactly. That was Top Gun. Now it has survived Bond.',
    reinforces: 'comigo',
    chipHint: 'comigo',
  },
  {
    id: 'B31',
    name: 'CLARO returns',
    stage: 'EXTRACTION',
    timecode: '05:57–06:09',
    purpose: 'Reinforce conversational glue in a natural reply.',
    type: 'choice',
    context: 'Podes vir amanhã?',
    headline: 'Of course.',
    options: [
      { id: 'claro', pt: 'Claro.', correct: true },
      { id: 'porque_nao', pt: 'Porque não?', feedback: 'This is certainty, not “why not?”.' },
      { id: 'quando', pt: 'Quando?', feedback: 'This is certainty, not a question about time.' },
    ],
    reveal: 'Claro. Tiny piece. Second world.',
    reinforces: 'claro',
    chipHint: 'claro',
  },
  {
    id: 'B32',
    name: 'Mixed recall',
    stage: 'EXTRACTION',
    timecode: '06:09–06:37',
    purpose: 'Create interference and test whether old and new labels retrieve rapidly.',
    type: 'recall-burst',
    checkpoint: 2,
    eyebrow: 'SIX QUICK ONES.',
    sub: 'No film lines. Just meaning.',
    cards: [
      { cue: 'my name is', answer: 'chamo_me', options: ['chamo_me', 'queria', 'posso'] },
      { cue: 'I’d like', answer: 'queria', options: ['posso', 'queria', 'onde_fica'] },
      { cue: 'can I', answer: 'posso', options: ['podes', 'posso', 'amanha'] },
      { cue: 'where is', answer: 'onde_fica', options: ['outra_vez', 'onde_fica', 'chamo_me'] },
      { cue: 'tomorrow', answer: 'amanha', options: ['amanha', 'quando', 'outra_vez'] },
      { cue: 'again', answer: 'outra_vez', options: ['queria', 'amanha', 'outra_vez'] },
    ],
    reveal: 'Good. Now let’s see if they work outside Bond.',
    capture: ['bond_mixed_recall'],
  },

  // -------------------------------------------------------------- REAL WORLD
  {
    id: 'B33',
    name: 'Bond transfer 01',
    stage: 'REAL WORLD',
    timecode: '06:37–06:53',
    purpose: 'Cold transfer of identity and ordering.',
    type: 'composite',
    context: 'You walk into a café.',
    headline: 'Introduce yourself. Then order a coffee.',
    parts: [
      {
        kind: 'tiles',
        id: 'name',
        prompt: 'My name is Ana.',
        tiles: [
          { id: 'chamo_me', text: 'Chamo-me' },
          { id: 'ana', text: 'Ana' },
        ],
        answer: ['chamo_me', 'ana'],
        hint1: 'Start with your “my name is…” block.',
        chipHint: 'chamo_me',
      },
      {
        kind: 'tiles',
        id: 'order',
        prompt: 'I’d like a coffee.',
        tiles: [
          { id: 'queria', text: 'Queria' },
          { id: 'um_cafe', text: 'um café' },
        ],
        answer: ['queria', 'um_cafe'],
        hint1: 'Start with your polite “I’d like…” block.',
        chipHint: 'queria',
      },
    ],
    reveal: 'No Bond required.',
    capture: ['bond_transfer'],
  },
  {
    id: 'B34',
    name: 'Bond transfer 02',
    stage: 'REAL WORLD',
    timecode: '06:53–07:09',
    purpose: 'Cold transfer of permission and location.',
    type: 'composite',
    context: 'At a station.',
    headline: 'Ask to pay. Then ask for the exit.',
    parts: [
      {
        kind: 'tiles',
        id: 'pay',
        prompt: 'Can I pay?',
        tiles: [
          { id: 'posso', text: 'Posso' },
          { id: 'pagar', text: 'pagar' },
          { id: 'q', text: '?' },
        ],
        answer: ['posso', 'pagar', 'q'],
        hint1: 'Your “can I…?” block leads.',
        chipHint: 'posso',
      },
      {
        kind: 'tiles',
        id: 'exit',
        prompt: 'Where is the exit?',
        note: 'a saída = the exit',
        tiles: [
          { id: 'onde_fica', text: 'Onde fica' },
          { id: 'a_saida', text: 'a saída' },
          { id: 'q2', text: '?' },
        ],
        answer: ['onde_fica', 'a_saida', 'q2'],
        hint1: 'Your “where is…?” block leads.',
        chipHint: 'onde_fica',
      },
    ],
    reveal: 'Permission. Location. Real language.',
    capture: ['bond_transfer'],
  },
  {
    id: 'B35',
    name: 'Bond transfer 03',
    stage: 'REAL WORLD',
    timecode: '07:09–07:25',
    purpose: 'Cold transfer of time and repetition while reusing Top Gun structure.',
    type: 'composite',
    context: 'Your friend asks when. Then you miss what they say.',
    headline: 'Answer, then ask them to say it again.',
    parts: [
      {
        kind: 'choice',
        id: 'when',
        prompt: 'Quando vamos?',
        options: [
          { id: 'amanha', pt: 'Amanhã.', correct: true },
          { id: 'outra_vez', pt: 'Outra vez.', feedback: 'That means “again”. They asked when.' },
          { id: 'claro', pt: 'Claro.', feedback: 'That agrees but gives no time.' },
        ],
        chipHint: 'amanha',
      },
      {
        kind: 'tiles',
        id: 'again',
        prompt: 'Can you say it again?',
        note: 'dizer = to say',
        tiles: [
          { id: 'podes', text: 'Podes' },
          { id: 'dizer', text: 'dizer' },
          { id: 'outra_vez', text: 'outra vez' },
          { id: 'q', text: '?' },
        ],
        answer: ['podes', 'dizer', 'outra_vez', 'q'],
        hint1: 'Old request. New repeat phrase.',
        chipHint: 'outra_vez',
      },
    ],
    reveal: 'One answer from Bond. One sentence built from Bond and Top Gun.',
    combines: ['amanha', 'outra_vez'],
    capture: ['bond_transfer'],
  },
  {
    id: 'B36',
    name: 'Compound inventory reveal',
    stage: 'REAL WORLD',
    timecode: '07:25–07:47',
    purpose: 'Make accumulation and reinforcement visible.',
    type: 'compound-inventory',
    eyebrow: 'YOUR PORTUGUESE',
    closing:
      'Bond added six new pieces. Top Gun did not disappear. It became infrastructure.',
    sub: 'A transparent count of tested building blocks. Not a fluency score.',
    cta: 'SHOW ME WHAT THEY CAN DO TOGETHER',
    capture: ['compound_inventory_view'],
  },
  {
    id: 'B37',
    name: 'Transition to crossover',
    stage: 'REAL WORLD',
    timecode: '07:47–07:59',
    purpose: 'Explicitly remove both cultural worlds before the compound test.',
    type: 'briefing',
    headline: 'Now we take both films away.',
    sub: 'No Maverick. No Bond. Just you, in Portuguese.',
    cta: 'LET’S GO',
    neutral: {
      headline: 'Now we take the lesson away.',
      sub: 'Just you, in Portuguese.',
    },
    capture: ['crossover_start'],
  },

  // --------------------------------------------------------------- CROSSOVER
  // From here the cultural framing is gone. Nothing below names either property.
  {
    id: 'C01',
    name: 'Crossover premise',
    stage: 'CROSSOVER',
    timecode: '07:59–08:09',
    purpose: 'Frame combination once, then remove every cultural cue.',
    type: 'briefing',
    eyebrow: 'TWO WORLDS. ONE PORTUGUESE.',
    headline: 'You are going to build things neither one taught you as a line.',
    sub: 'You are not going to quote anything.',
    cta: 'START',
    capture: ['crossover_begin'],
  },
  {
    id: 'C02',
    name: 'Old + old',
    stage: 'CROSSOVER',
    timecode: '08:09–08:21',
    purpose: 'Establish confidence with a combination from the first world.',
    type: 'tiles',
    headline: 'Can you come with me?',
    note: 'vir = to come',
    tiles: [
      { id: 'podes', text: 'Podes' },
      { id: 'vir', text: 'vir' },
      { id: 'comigo', text: 'comigo' },
      { id: 'q', text: '?' },
    ],
    answer: ['podes', 'vir', 'comigo', 'q'],
    hint1: 'Both key pieces are already yours.',
    reveal: 'Good. Now mix worlds.',
    chipHint: 'podes',
    combines: ['podes', 'comigo'],
  },
  {
    id: 'C03',
    name: 'Old + new',
    stage: 'CROSSOVER',
    timecode: '08:21–08:35',
    purpose:
      'Combine an old request, an old pronoun and a new repeat phrase into a line no mission taught.',
    type: 'tiles',
    headline: 'Can you come with me again?',
    note: 'vir = to come',
    tiles: [
      { id: 'podes', text: 'Podes' },
      { id: 'vir', text: 'vir' },
      { id: 'comigo', text: 'comigo' },
      { id: 'outra_vez', text: 'outra vez' },
      { id: 'q', text: '?' },
    ],
    answer: ['podes', 'vir', 'comigo', 'outra_vez', 'q'],
    rules: [
      { when: 'omits', tile: 'outra_vez', message: 'You have built “Can you come with me?” Now add “again”.' },
      { when: 'not-first', tile: 'podes', message: 'Old request first.' },
    ],
    reveal: 'That sentence did not belong to either world.',
    chipHint: 'outra_vez',
    combines: ['podes', 'comigo', 'outra_vez'],
  },
  {
    id: 'C04',
    name: 'Need + location',
    stage: 'CROSSOVER',
    timecode: '08:35–08:51',
    purpose: 'Combine one block from each world in an ordinary travel task.',
    type: 'composite',
    context: 'You need to travel.',
    headline: 'Say what you need. Then ask where to go.',
    parts: [
      {
        kind: 'tiles',
        id: 'need',
        prompt: 'I need a ticket.',
        note: 'um bilhete = a ticket',
        tiles: [
          { id: 'preciso', text: 'Preciso' },
          { id: 'de', text: 'de' },
          { id: 'um_bilhete', text: 'um bilhete' },
        ],
        answer: ['preciso', 'de', 'um_bilhete'],
        hint1: 'Keep your “I need…” block together.',
        chipHint: 'preciso_de',
      },
      {
        kind: 'tiles',
        id: 'where',
        prompt: 'Where is the bus stop?',
        note: 'a paragem = the bus stop',
        tiles: [
          { id: 'onde_fica', text: 'Onde fica' },
          { id: 'a_paragem', text: 'a paragem' },
          { id: 'q', text: '?' },
        ],
        answer: ['onde_fica', 'a_paragem', 'q'],
        hint1: 'Your “where is…?” block leads.',
        chipHint: 'onde_fica',
      },
    ],
    reveal: 'This is the product claim in one ordinary problem.',
    combines: ['preciso_de', 'onde_fica'],
  },
  {
    id: 'C05',
    name: 'Time combination',
    stage: 'CROSSOVER',
    timecode: '08:51–09:03',
    purpose: 'Combine an old question hinge with a new time word.',
    type: 'composite',
    context: 'Making plans.',
    headline: 'Ask when. Then answer it.',
    parts: [
      {
        kind: 'tiles',
        id: 'ask',
        prompt: 'When are we going?',
        note: 'vamos = we’re going',
        tiles: [
          { id: 'quando', text: 'Quando' },
          { id: 'vamos', text: 'vamos' },
          { id: 'q', text: '?' },
        ],
        answer: ['quando', 'vamos', 'q'],
        hint1: 'The question hinge leads.',
        chipHint: 'quando',
      },
      {
        kind: 'choice',
        id: 'answer',
        prompt: 'Answer it: tomorrow.',
        options: [
          { id: 'amanha', pt: 'Amanhã.', correct: true },
          { id: 'quando', pt: 'Quando.', feedback: 'That asks. It does not answer.' },
          { id: 'outra_vez', pt: 'Outra vez.', feedback: 'That means “again”.' },
        ],
        chipHint: 'amanha',
      },
    ],
    reveal: 'Old hinge. New answer.',
    combines: ['quando', 'amanha'],
  },
  {
    id: 'C06',
    name: 'Permission + everyday action',
    stage: 'CROSSOVER',
    timecode: '09:03–09:15',
    purpose: 'Use the permission block with a verb it was never taught alongside.',
    type: 'tiles',
    context: 'The door is closed.',
    headline: 'Can I come in?',
    note: 'entrar = to come in',
    tiles: [
      { id: 'posso', text: 'Posso' },
      { id: 'entrar', text: 'entrar' },
      { id: 'q', text: '?' },
      { id: 'podes', text: 'Podes', distractor: true },
    ],
    answer: ['posso', 'entrar', 'q'],
    rules: [
      { when: 'uses', tile: 'podes', message: 'That asks whether they can. You are asking about yourself.' },
    ],
    hint1: '“Can I…” starts with your permission block.',
    reveal: 'Exactly.',
    chipHint: 'posso',
  },
  {
    id: 'C07',
    name: 'Conversation recovery',
    stage: 'CROSSOVER',
    timecode: '09:15–09:29',
    purpose: 'Use an old survival block and then a new repeat block.',
    type: 'composite',
    context: 'Someone speaks too fast.',
    headline: 'Say you cannot follow. Then ask to hear it again.',
    parts: [
      {
        kind: 'tiles',
        id: 'cant',
        prompt: 'I can’t understand.',
        tiles: [
          { id: 'nao_consigo', text: 'Não consigo' },
          { id: 'perceber', text: 'perceber' },
        ],
        answer: ['nao_consigo', 'perceber'],
        hint1: 'Start with your “I can’t…” block.',
        chipHint: 'nao_consigo',
      },
      {
        kind: 'tiles',
        id: 'again',
        prompt: 'Can I hear it again?',
        note: 'ouvir = to hear',
        tiles: [
          { id: 'posso', text: 'Posso' },
          { id: 'ouvir', text: 'ouvir' },
          { id: 'outra_vez', text: 'outra vez' },
          { id: 'q', text: '?' },
        ],
        answer: ['posso', 'ouvir', 'outra_vez', 'q'],
        hint1: 'Ask permission, then use your “again” block.',
        chipHint: 'outra_vez',
      },
    ],
    reveal: 'That is functional conversation, not translation.',
    combines: ['nao_consigo', 'posso', 'outra_vez'],
  },
  {
    id: 'C08',
    name: 'Social response',
    stage: 'CROSSOVER',
    timecode: '09:29–09:39',
    purpose: 'Retrieve two small conversational pieces under minimal context.',
    type: 'composite',
    context: 'Another coffee?',
    headline: 'Agree. Then say why not.',
    parts: [
      {
        kind: 'choice',
        id: 'certainty',
        prompt: 'Of course.',
        options: [
          { id: 'claro', pt: 'Claro.', correct: true },
          { id: 'porque_nao', pt: 'Porque não?', feedback: 'First certainty. Then openness.' },
          { id: 'amanha', pt: 'Amanhã.', feedback: 'That is a time, not agreement.' },
        ],
        chipHint: 'claro',
      },
      {
        kind: 'choice',
        id: 'openness',
        prompt: 'Why not?',
        options: [
          { id: 'porque_nao', pt: 'Porque não?', correct: true },
          { id: 'claro', pt: 'Claro.', feedback: 'You already said that one.' },
          { id: 'quando', pt: 'Quando?', feedback: 'That asks about time.' },
        ],
        chipHint: 'porque_nao',
      },
    ],
    reveal: 'Tiny phrases carry a lot of human conversation.',
    combines: ['claro', 'porque_nao'],
  },
  {
    id: 'C09',
    name: 'No-culture composite',
    stage: 'CROSSOVER',
    timecode: '09:39–09:57',
    purpose: 'Final culture-free construction under one realistic context.',
    type: 'composite',
    hideSourcesUntilDone: true,
    eyebrow: 'NO FILMS NOW.',
    context: 'You arrive in a town you do not know.',
    headline: 'Say three things.',
    parts: [
      {
        kind: 'tiles',
        id: 'name',
        prompt: 'My name is Sofia.',
        tiles: [
          { id: 'chamo_me', text: 'Chamo-me' },
          { id: 'sofia', text: 'Sofia' },
        ],
        answer: ['chamo_me', 'sofia'],
        hint1: 'Your introduction block.',
        chipHint: 'chamo_me',
      },
      {
        kind: 'tiles',
        id: 'order',
        prompt: 'I’d like a tea.',
        note: 'um chá = a tea',
        tiles: [
          { id: 'queria', text: 'Queria' },
          { id: 'um_cha', text: 'um chá' },
        ],
        answer: ['queria', 'um_cha'],
        hint1: 'Your polite “I’d like…” block.',
        chipHint: 'queria',
      },
      {
        kind: 'tiles',
        id: 'where',
        prompt: 'Where is the hotel?',
        note: 'o hotel = the hotel',
        tiles: [
          { id: 'onde_fica', text: 'Onde fica' },
          { id: 'o_hotel', text: 'o hotel' },
          { id: 'q', text: '?' },
        ],
        answer: ['onde_fica', 'o_hotel', 'q'],
        hint1: 'Your “where is…?” block.',
        chipHint: 'onde_fica',
      },
    ],
    reveal: 'Three ordinary sentences. The scaffolding is gone.',
    combines: ['chamo_me', 'queria', 'onde_fica'],
  },
  {
    id: 'C10',
    name: 'Compound result',
    stage: 'CROSSOVER',
    timecode: '09:57–10:07',
    purpose: 'Express evidence without overclaiming fluency.',
    type: 'crossover-result',
    eyebrow: 'WHAT YOU JUST DID',
    cta: 'SHOW MY DECK',
    lowScoreCopy:
      'Some combined cleanly. Some need another encounter. That is useful data, not a grade.',
    capture: ['crossover_score'],
  },
  {
    id: 'C11',
    name: 'Mental-model check',
    stage: 'CROSSOVER',
    timecode: '10:07–10:17',
    purpose: 'Test whether the learner understood the intended mechanism.',
    type: 'scale',
    eyebrow: 'ONE IMPORTANT QUESTION.',
    headline: 'What did that feel like?',
    points: [
      { value: 1, label: 'Mostly remembering film material' },
      { value: 2, label: 'Mostly remembering, a bit of building' },
      { value: 3, label: 'An even mix' },
      { value: 4, label: 'Mostly building, a bit of remembering' },
      { value: 5, label: 'Mostly speaking and building Portuguese' },
    ],
    field: 'mental_model_transfer',
    cta: 'CONTINUE',
  },
  {
    id: 'C12',
    name: 'Desire + next world',
    stage: 'CROSSOVER',
    timecode: '10:17–10:32',
    purpose: 'Capture continuation intent after the evidence, not before it.',
    type: 'post-intent',
    headline: 'What would you do next?',
    options: [
      { id: 'another_world', label: 'ANOTHER CULTURAL WORLD' },
      { id: 'review_deck', label: 'REVIEW MY DECK' },
      { id: 'both', label: 'BOTH' },
      { id: 'neither', label: 'NEITHER' },
    ],
    followUp: 'What should the next world be?',
    cta: 'FINISH',
    capture: ['post_experience_intent', 'next_world_post'],
  },
]

/** Screens whose result feeds the cross-world transfer metric (§12). */
export const CROSSOVER_ITEMS = [
  'C02',
  'C03',
  'C04',
  'C05',
  'C06',
  'C07',
  'C08',
  'C09',
]

/** Cold retrieval before any cue from the first world (§7 B02–B05, extended). */
export const COLD_RECALL_ITEMS = ['B02', 'B03', 'B04', 'B04A', 'B05', 'B05A']

/** Bond-only transfer, with the hook removed but the second world still present. */
export const BOND_TRANSFER_ITEMS = ['B14', 'B17', 'B20', 'B29', 'B33', 'B34', 'B35']

export const MISSION_02: Mission = {
  mission_id: 'mission_02',
  property_id: 'james_bond',
  property_label: 'James Bond',
  locale: 'pt-PT',
  targets_new: ['chamo_me', 'queria', 'posso', 'onde_fica', 'amanha', 'outra_vez'],
  targets_reinforced: ['comigo', 'podes', 'quando', 'claro'],
  stages: [
    'RETURN',
    'AFFINITY',
    'BRIEFING',
    'CONTACT',
    'FIELDWORK',
    'EXTRACTION',
    'REAL WORLD',
    'CROSSOVER',
  ],
  screens: SCREENS,
  transfer_items: BOND_TRANSFER_ITEMS,
  crossover_items: CROSSOVER_ITEMS,
  cold_recall_items: COLD_RECALL_ITEMS,
}
