import type { Mission, Screen } from '../types'
import { BRAND } from '../brand'

/**
 * Mission 01 — Top Gun / European Portuguese.
 * Build copy from spec §8 and §9. Every screen below is data: no lesson text lives
 * in JSX (Appendix B, item 1), so a native-reviewer correction is a one-line edit.
 *
 * Render contract for the shared fields:
 *   eyebrow     tiny caps label
 *   hook        brief cultural reference, shown in quotes
 *   context     scene-setting line above the prompt
 *   headline    the large prompt (English) or statement
 *   headlinePt  the large prompt in Portuguese — always dominant over English
 *   note        supporting gloss, e.g. "água = water"
 *   sub         muted supporting line
 */
export const SCREENS: Screen[] = [
  // -------------------------------------------------------------- PRE-FLIGHT
  {
    id: 'S01',
    name: 'Opening promise',
    stage: 'PRE-FLIGHT',
    timecode: '00:00–00:10',
    purpose: 'Establish the proposition in one glance.',
    type: 'promise',
    wordmark: BRAND.name,
    headline: 'Learn Portuguese through something you already know.',
    sub: '10 minutes. One film. Language you can actually use.',
    cta: 'START A MISSION',
    capture: ['session_start', 'landing_cta_tap'],
  },
  {
    id: 'S02',
    name: 'Choose the world',
    stage: 'PRE-FLIGHT',
    timecode: '00:10–00:20',
    purpose: 'Make culture the entry point before language mechanics.',
    type: 'culture-select',
    headline: 'What do you know by heart?',
    cards: [
      { id: 'top_gun', title: 'TOP GUN', meta: 'Mission 01 · Portuguese (Portugal) · 10 min', active: true },
      { id: 'friends', title: 'FRIENDS', meta: 'Coming soon', active: false },
      { id: 'james_bond', title: 'JAMES BOND', meta: 'Coming soon', active: false },
      { id: 'football', title: 'FOOTBALL', meta: 'Coming soon', active: false },
    ],
    cta: 'FLY THIS ONE',
    capture: ['culture_selected'],
  },
  {
    id: 'S03',
    name: 'Familiarity capture',
    stage: 'PRE-FLIGHT',
    timecode: '00:20–00:30',
    purpose: 'Create the key independent variable for the prototype study.',
    type: 'familiarity',
    headline: 'How well do you know Top Gun?',
    sub: 'No right answer. This helps us see whether familiarity changes how you learn.',
    options: [
      { id: 'high', label: 'KNOW IT BY HEART' },
      { id: 'medium', label: 'SEEN IT A FEW TIMES' },
      { id: 'low', label: 'BARELY OR NEVER' },
    ],
    reveal: 'Perfect. Let’s see what your memory can do.',
    capture: ['top_gun_familiarity'],
  },
  {
    id: 'S04',
    name: 'Mission briefing',
    stage: 'PRE-FLIGHT',
    timecode: '00:30–00:40',
    purpose: 'Explain the mechanic without sounding instructional.',
    type: 'briefing',
    eyebrow: 'YOUR MISSION',
    headline: 'Steal 10 useful pieces of Portuguese from a film you already know.',
    sub: 'First you’ll meet them inside Top Gun. Then the film disappears. If you can still use them, they’re yours.',
    cta: 'LET’S FLY',
    capture: ['briefing_continue'],
  },

  // --------------------------------------------------------------- TAKE-OFF
  {
    id: 'S05',
    name: 'Cultural hook 01 — COMIGO',
    stage: 'TAKE-OFF',
    timecode: '00:40–00:52',
    purpose: 'Use a highly recognisable line to create the first attachment.',
    type: 'choice',
    hook: 'TALK TO ME, GOOSE.',
    sub: 'You know the moment. Which Portuguese line means “Talk to me”?',
    options: [
      { id: 'fala', pt: 'Fala comigo.', correct: true },
      { id: 'vem', pt: 'Vem comigo.', feedback: 'Vem = come. You’ve chosen “Come with me.” Try again.' },
      { id: 'fica', pt: 'Fica comigo.', feedback: 'Fica = stay. You’ve chosen “Stay with me.” Try again.' },
    ],
    reveal: 'Exactly. Fala comigo. Tap the speaker to hear it.',
  },
  {
    id: 'S06',
    name: 'Discover COMIGO',
    stage: 'TAKE-OFF',
    timecode: '00:52–01:02',
    purpose: 'Extract the reusable block from the movie phrase.',
    type: 'block-intro',
    phrase: { pt: 'Fala comigo.' },
    blocks: [{ id: 'comigo', pt: 'comigo', gloss: 'with me' }],
    sub: 'Keep comigo. The verb can change.',
    tapPrompt: 'Tap COMIGO to bank it.',
    cta: 'CONTINUE',
    reveal: 'One piece of Portuguese. Now make it move.',
    acquires: 'comigo',
  },
  {
    id: 'S07',
    name: 'Manipulate COMIGO',
    stage: 'TAKE-OFF',
    timecode: '01:02–01:14',
    purpose: 'Show that one block survives while the verb changes.',
    type: 'choice',
    headline: 'Come with me.',
    sub: 'Which one?',
    options: [
      { id: 'vem', pt: 'Vem comigo.', correct: true },
      { id: 'fala', pt: 'Fala comigo.', feedback: 'That’s “Talk to me.” Same comigo, wrong verb.' },
      { id: 'fica', pt: 'Fica comigo.', feedback: 'That’s “Stay with me.” Same comigo, wrong verb.' },
    ],
    reveal: 'Vem comigo. Same comigo. New verb.',
    chipHint: 'comigo',
  },
  {
    id: 'S08',
    name: 'Escape the film — COMIGO',
    stage: 'TAKE-OFF',
    timecode: '01:14–01:25',
    purpose: 'Prove immediate transfer into an ordinary situation.',
    type: 'tiles',
    context: 'No jets. Just a café. You stand up and tell a friend:',
    headline: '“Come with me.”',
    tiles: [
      { id: 'vem', text: 'Vem' },
      { id: 'comigo', text: 'comigo' },
      { id: 'amanha', text: 'amanhã', distractor: true },
    ],
    answer: ['vem', 'comigo'],
    rules: [
      { when: 'uses', tile: 'amanha', message: 'amanhã = tomorrow. Useful, but not needed here.' },
      { when: 'order', message: 'Portuguese wants the verb first here: Vem comigo.' },
    ],
    reveal: 'That’s the trick. Top Gun got you to comigo. The café proves it belongs to you.',
    chipHint: 'comigo',
    capture: ['transfer=comigo'],
  },
  {
    id: 'S09',
    name: 'Cultural hook 02 — PODES',
    stage: 'TAKE-OFF',
    timecode: '01:25–01:35',
    purpose: 'Extract a high-frequency ability/request hinge from the wingman line.',
    type: 'block-intro',
    hook: 'YOU CAN BE MY WINGMAN ANYTIME.',
    sub: 'Forget “wingman”. The useful part is “you can”.',
    blocks: [{ id: 'podes', pt: 'podes', gloss: 'you can / can you' }],
    tapPrompt: 'Tap PODES to hear and continue.',
    cta: 'CONTINUE',
    reveal: 'Podes turns into a huge number of useful questions.',
    introduces: 'podes',
  },
  {
    id: 'S10',
    name: 'Build with PODES',
    stage: 'TAKE-OFF',
    timecode: '01:35–01:48',
    purpose: 'Combine two acquired pieces into the learner’s first generative sentence.',
    type: 'tiles',
    headline: 'Can you come with me?',
    sub: 'You already know both important pieces.',
    note: 'vir = to come',
    tiles: [
      { id: 'podes', text: 'Podes' },
      { id: 'vir', text: 'vir' },
      { id: 'comigo', text: 'comigo' },
      { id: 'q', text: '?' },
    ],
    answer: ['podes', 'vir', 'comigo', 'q'],
    rules: [
      { when: 'not-first', tile: 'podes', message: 'Start with the hinge: Podes… = Can you…?' },
      { when: 'omits', tile: 'comigo', message: 'You’ve built “Can you come?” Add “with me”.' },
    ],
    reveal: 'Podes vir comigo? Two pieces, one new sentence.',
    acquires: 'podes',
    capture: ['composition=podes+comigo'],
  },
  {
    id: 'S11',
    name: 'Escape the film — PODES',
    stage: 'TAKE-OFF',
    timecode: '01:48–02:00',
    purpose: 'Use PODES as a practical repair strategy for real conversation.',
    type: 'tiles',
    context: 'Someone says something too fast.',
    headline: '“Can you repeat?”',
    note: 'repetir = repeat',
    tiles: [
      { id: 'podes', text: 'Podes' },
      { id: 'repetir', text: 'repetir' },
      { id: 'q', text: '?' },
    ],
    answer: ['podes', 'repetir', 'q'],
    rules: [
      { when: 'omits', tile: 'podes', message: 'repetir is only “repeat”. Make it a question with Podes.' },
      { when: 'order', message: 'Lead with Podes: Podes repetir?' },
    ],
    reveal: 'Podes repetir? This one may save you tonight.',
    chipHint: 'podes',
    capture: ['transfer=podes'],
  },

  // ------------------------------------------------------------------ CRUISE
  {
    id: 'S12',
    name: 'Cultural hook 03 — PRECISO DE',
    stage: 'CRUISE',
    timecode: '02:00–02:12',
    purpose: 'Demonstrate the product’s “usefulness over subtitle fidelity” principle.',
    type: 'block-intro',
    hook: 'I FEEL THE NEED…',
    sub: 'A subtitle chases the joke. We’re chasing language you’ll actually use.',
    blocks: [{ id: 'preciso_de', pt: 'preciso de…', gloss: 'I need…' }],
    tapPrompt: 'Tap PRECISO DE to hear it.',
    cta: 'CONTINUE',
    reveal: 'Treat preciso de as one block for now. Grammar can wait.',
    introduces: 'preciso_de',
  },
  {
    id: 'S13',
    name: 'Build with PRECISO DE',
    stage: 'CRUISE',
    timecode: '02:12–02:25',
    purpose: 'Attach a common noun to the new block.',
    type: 'choice',
    headline: 'I need water.',
    note: 'água = water',
    options: [
      { id: 'preciso_de_agua', pt: 'Preciso de água.', correct: true },
      { id: 'preciso_agua', pt: 'Preciso água.', feedback: 'Keep the whole block: preciso de…' },
      { id: 'tenho_de_agua', pt: 'Tenho de água.', feedback: 'Not this time. The block you banked is preciso de.' },
    ],
    reveal: 'Preciso de água. Keep the de attached.',
    acquires: 'preciso_de',
  },
  {
    id: 'S14',
    name: 'Escape the film — PRECISO DE',
    stage: 'CRUISE',
    timecode: '02:25–02:38',
    purpose: 'Transfer immediately into a travel use case.',
    type: 'tiles',
    context: 'Taxi rank. No Maverick.',
    headline: '“I need a taxi.”',
    note: 'um táxi = a taxi',
    tiles: [
      { id: 'preciso', text: 'Preciso' },
      { id: 'de', text: 'de' },
      { id: 'um_taxi', text: 'um táxi' },
    ],
    answer: ['preciso', 'de', 'um_taxi'],
    rules: [
      { when: 'omits', tile: 'de', message: 'Keep preciso de together.' },
      { when: 'order', message: 'Build from the block first: Preciso de…' },
    ],
    reveal: 'Preciso de um táxi. Three minutes ago you couldn’t say that.',
    chipHint: 'preciso_de',
    capture: ['transfer=preciso_de'],
  },
  {
    id: 'S15',
    name: 'Maverick check 01',
    stage: 'CRUISE',
    timecode: '02:38–02:55',
    purpose: 'Introduce delayed retrieval before adding more material.',
    type: 'recall-burst',
    checkpoint: 1,
    eyebrow: 'MAVERICK CHECK',
    sub: 'No film clues. Three quick retrieves.',
    cards: [
      { cue: 'with me', answer: 'comigo', options: ['comigo', 'podes', 'preciso_de'] },
      { cue: 'Can you…?', answer: 'podes', options: ['preciso_de', 'podes', 'comigo'] },
      { cue: 'I need…', answer: 'preciso_de', options: ['podes', 'comigo', 'preciso_de'] },
    ],
    reveal: 'Good. Three pieces are already surviving without the scene.',
  },
  {
    id: 'S16',
    name: 'Inventory checkpoint',
    stage: 'CRUISE',
    timecode: '02:55–03:05',
    purpose: 'Make accumulation visible and create generative confidence.',
    type: 'inventory',
    view: 'inventory_view_1',
    eyebrow: 'YOUR PORTUGUESE',
    caption: 'Already enough for: Podes vir comigo? / Preciso de água.',
    cta: 'CONTINUE',
    reveal: 'Three pieces. More combinations than memorised lines.',
  },
  {
    id: 'S17',
    name: 'Cultural hook 04 — NÃO CONSIGO',
    stage: 'CRUISE',
    timecode: '03:05–03:17',
    purpose: 'Teach a powerful “I can’t manage to” repair block using communications failure as thematic memory.',
    type: 'block-intro',
    context: 'Sometimes the problem isn’t that you don’t know. It’s that you can’t.',
    blocks: [{ id: 'nao_consigo', pt: 'não consigo…', gloss: 'I can’t / I can’t manage to…' }],
    tapPrompt: 'Tap to hear it.',
    cta: 'CONTINUE',
    reveal: 'This is one of the most useful survival blocks in Portuguese.',
    introduces: 'nao_consigo',
  },
  {
    id: 'S18',
    name: 'Build with NÃO CONSIGO',
    stage: 'CRUISE',
    timecode: '03:17–03:30',
    purpose: 'Turn the block into a real conversational rescue phrase.',
    type: 'tiles',
    headline: 'I can’t understand.',
    note: 'perceber = understand',
    tiles: [
      { id: 'nao_consigo', text: 'Não consigo' },
      { id: 'perceber', text: 'perceber' },
      { id: 'consigo', text: 'consigo', distractor: true },
    ],
    answer: ['nao_consigo', 'perceber'],
    rules: [
      { when: 'uses', tile: 'consigo', message: 'consigo = I can manage. You need the negative block.' },
      { when: 'order', message: 'Start with the block: Não consigo…' },
    ],
    reveal: 'Não consigo perceber. Tap to hear it naturally.',
    acquires: 'nao_consigo',
  },
  {
    id: 'S19',
    name: 'Escape the film — NÃO CONSIGO',
    stage: 'CRUISE',
    timecode: '03:30–03:42',
    purpose: 'Show the same block working in a totally different domain.',
    type: 'tiles',
    context: '3 a.m. The room is too hot.',
    headline: '“I can’t sleep.”',
    note: 'dormir = sleep',
    tiles: [
      { id: 'nao_consigo', text: 'Não consigo' },
      { id: 'dormir', text: 'dormir' },
      { id: 'consigo', text: 'consigo', distractor: true },
    ],
    answer: ['nao_consigo', 'dormir'],
    rules: [
      { when: 'uses', tile: 'consigo', message: 'That says “I can sleep”. Add não.' },
      { when: 'omits', tile: 'nao_consigo', message: 'That is “sleep”. Build the whole thought.' },
    ],
    reveal: 'Same engine. Completely different situation.',
    chipHint: 'nao_consigo',
    capture: ['transfer=nao_consigo'],
  },
  {
    id: 'S20',
    name: 'Cultural hook 05 — PERDI',
    stage: 'CRUISE',
    timecode: '03:42–03:54',
    purpose: 'Use a memorable romance line to bank an everyday past-tense verb without teaching a tense system.',
    type: 'block-intro',
    hook: 'SHE’S LOST THAT LOVING FEELING.',
    sub: 'The romance is memorable. The useful verb is perder — to lose.',
    blocks: [{ id: 'perdi', pt: 'perdi', gloss: 'I lost' }],
    tapPrompt: 'Tap PERDI to hear it.',
    cta: 'CONTINUE',
    reveal: 'Today we only need one form: perdi = I lost.',
    introduces: 'perdi',
  },
  {
    id: 'S21',
    name: 'Build with PERDI',
    stage: 'CRUISE',
    timecode: '03:54–04:07',
    purpose: 'Anchor PERDI to a frequent travel problem.',
    type: 'choice',
    headline: 'I lost my keys.',
    note: 'as chaves = the keys',
    options: [
      { id: 'perdi_as_chaves', pt: 'Perdi as chaves.', correct: true },
      { id: 'perdeu_as_chaves', pt: 'Perdeu as chaves.', feedback: 'perdeu = he/she lost. You need perdi = I lost.' },
      { id: 'perdi_as_chave', pt: 'Perdi as chave.', feedback: 'The block is right. Keys is plural: as chaves.' },
    ],
    reveal: 'Perdi as chaves.',
    acquires: 'perdi',
  },
  {
    id: 'S22',
    name: 'Escape the film — PERDI',
    stage: 'CRUISE',
    timecode: '04:07–04:20',
    purpose: 'Transfer PERDI to a second common travel noun.',
    type: 'tiles',
    context: 'At the station.',
    headline: '“I lost my ticket.”',
    note: 'o bilhete = the ticket',
    tiles: [
      { id: 'perdi', text: 'Perdi' },
      { id: 'o_bilhete', text: 'o bilhete' },
      { id: 'perdeu', text: 'Perdeu', distractor: true },
    ],
    answer: ['perdi', 'o_bilhete'],
    rules: [
      { when: 'uses', tile: 'perdeu', message: 'That is he/she lost. You are speaking: perdi.' },
    ],
    reveal: 'Perdi o bilhete. One verb; a thousand things you can lose.',
    chipHint: 'perdi',
    capture: ['transfer=perdi'],
  },
  {
    id: 'S23',
    name: 'Cultural hook 06 — NÃO VOU',
    stage: 'CRUISE',
    timecode: '04:20–04:32',
    purpose: 'Extract a productive intention pattern from the “not leaving my wingman” idea.',
    type: 'block-intro',
    hook: 'I’M NOT LEAVING MY WINGMAN.',
    sub: 'The reusable engine is bigger than the line.',
    blocks: [{ id: 'nao_vou', pt: 'não vou + verb', gloss: 'I’m not going to…' }],
    tapPrompt: 'Tap NÃO VOU to hear it.',
    cta: 'CONTINUE',
    reveal: 'Bank não vou. Add a verb and you have an intention.',
    introduces: 'nao_vou',
  },
  {
    id: 'S24',
    name: 'Build with NÃO VOU',
    stage: 'CRUISE',
    timecode: '04:32–04:45',
    purpose: 'Practice the pattern with a simple infinitive.',
    type: 'tiles',
    headline: 'I’m not going to wait.',
    note: 'esperar = wait',
    tiles: [
      { id: 'nao_vou', text: 'Não vou' },
      { id: 'esperar', text: 'esperar' },
      { id: 'vou', text: 'vou', distractor: true },
    ],
    answer: ['nao_vou', 'esperar'],
    rules: [
      { when: 'uses', tile: 'vou', message: 'That says “I’m going to wait.” You need não.' },
      { when: 'not-first', tile: 'nao_vou', message: 'Start with the engine: Não vou…' },
    ],
    reveal: 'Não vou esperar.',
    acquires: 'nao_vou',
  },
  {
    id: 'S25',
    name: 'Escape the film — NÃO VOU',
    stage: 'CRUISE',
    timecode: '04:45–04:58',
    purpose: 'Transfer intention to a social situation.',
    type: 'tiles',
    context: 'Your friend orders shots. You’re done.',
    headline: '“I’m not going to drink.”',
    note: 'beber = drink',
    tiles: [
      { id: 'nao_vou', text: 'Não vou' },
      { id: 'beber', text: 'beber' },
      { id: 'vou', text: 'vou', distractor: true },
    ],
    answer: ['nao_vou', 'beber'],
    rules: [
      { when: 'uses', tile: 'vou', message: 'That means you are going to drink. Add não.' },
    ],
    reveal: 'Não vou beber. Useful language. Potentially useful decision.',
    chipHint: 'nao_vou',
    capture: ['transfer=nao_vou'],
  },

  // --------------------------------------------------------- FINAL APPROACH
  {
    id: 'S26',
    name: 'Cultural hook 07 — O QUE ESTÁS A…?',
    stage: 'FINAL APPROACH',
    timecode: '04:58–05:12',
    purpose:
      'Use a familiar “what were you thinking?” energy to introduce a distinctly European Portuguese progressive pattern in the present.',
    type: 'block-intro',
    hook: 'WHAT WERE YOU THINKING?',
    sub: 'We’re not teaching that past tense yet. We’re stealing a pattern Portuguese uses all day.',
    blocks: [{ id: 'o_que_estas_a', pt: 'O que estás a…?', gloss: 'What are you …ing?' }],
    tapPrompt: 'Tap the pattern to hear it.',
    cta: 'CONTINUE',
    reveal: 'In Portugal, estás a + verb is a very common way to express “are …ing”.',
    introduces: 'o_que_estas_a',
  },
  {
    id: 'S27',
    name: 'Build the European Portuguese pattern',
    stage: 'FINAL APPROACH',
    timecode: '05:12–05:26',
    purpose: 'Apply the pattern with a familiar verb and reinforce the “a”.',
    type: 'choice',
    headline: 'What are you drinking?',
    note: 'beber = drink',
    options: [
      { id: 'estas_a_beber', pt: 'O que estás a beber?', correct: true },
      { id: 'estas_beber', pt: 'O que estás beber?', feedback: 'In Portugal, keep the a: estás a beber.' },
      { id: 'es_a_beber', pt: 'O que és a beber?', feedback: 'és = you are as an identity/state. This pattern needs estás a + verb.' },
    ],
    reveal: 'O que estás a beber?',
    acquires: 'o_que_estas_a',
  },
  {
    id: 'S28',
    name: 'Escape the film — O QUE ESTÁS A…?',
    stage: 'FINAL APPROACH',
    timecode: '05:26–05:40',
    purpose: 'Transfer the pattern to a general-purpose question.',
    type: 'tiles',
    context: 'Your friend is doing something inexplicable.',
    headline: '“What are you doing?”',
    note: 'fazer = do',
    tiles: [
      { id: 'o_que', text: 'O que' },
      { id: 'estas_a', text: 'estás a' },
      { id: 'fazer', text: 'fazer' },
      { id: 'q', text: '?' },
      { id: 'estas', text: 'estás', distractor: true },
    ],
    answer: ['o_que', 'estas_a', 'fazer', 'q'],
    rules: [
      { when: 'uses', tile: 'estas', message: 'Keep the Portuguese pattern together: estás a…' },
    ],
    reveal: 'O que estás a fazer? This pattern is now yours, not the film’s.',
    chipHint: 'o_que_estas_a',
    capture: ['transfer=o_que_estas_a'],
  },
  {
    id: 'S29',
    name: 'Cultural hook 08 — QUANDO',
    stage: 'FINAL APPROACH',
    timecode: '05:40–05:51',
    purpose: 'Bank a high-value hinge word without dragging the learner into an advanced clause.',
    type: 'block-intro',
    hook: 'WHEN I’M READY.',
    sub: 'Don’t learn the whole sentence yet. Bank the hinge.',
    blocks: [{ id: 'quando', pt: 'quando', gloss: 'when' }],
    tapPrompt: 'Tap QUANDO to hear it.',
    cta: 'CONTINUE',
    reveal: 'Small word. Enormous reach.',
    introduces: 'quando',
  },
  {
    id: 'S30',
    name: 'Build with QUANDO',
    stage: 'FINAL APPROACH',
    timecode: '05:51–06:03',
    purpose: 'Contrast WHEN with a plausible question-word distractor.',
    type: 'choice',
    headline: 'When are you going?',
    note: 'vais = you’re going / you go',
    options: [
      { id: 'quando_vais', pt: 'Quando vais?', correct: true },
      { id: 'onde_vais', pt: 'Onde vais?', feedback: 'Onde = where. You’ve asked “Where are you going?” We need when.' },
      { id: 'quem_vais', pt: 'Quem vais?', feedback: 'Quem = who. The hinge you banked is quando.' },
    ],
    reveal: 'Quando vais?',
    acquires: 'quando',
  },
  {
    id: 'S31',
    name: 'Escape the film — QUANDO',
    stage: 'FINAL APPROACH',
    timecode: '06:03–06:15',
    purpose: 'Use QUANDO in a second extremely simple question.',
    type: 'tiles',
    context: 'Friends are making dinner plans.',
    headline: '“When are we going?”',
    note: 'vamos = we’re going / we go',
    tiles: [
      { id: 'quando', text: 'Quando' },
      { id: 'vamos', text: 'vamos' },
      { id: 'q', text: '?' },
    ],
    answer: ['quando', 'vamos', 'q'],
    rules: [
      { when: 'omits', tile: 'quando', message: 'You’ve said “We’re going?” Add the question hinge: Quando.' },
    ],
    reveal: 'Quando vamos? Another useful question built from one tiny word.',
    chipHint: 'quando',
    capture: ['transfer=quando'],
  },
  {
    id: 'S32',
    name: 'Two tiny high-value boosters',
    stage: 'FINAL APPROACH',
    timecode: '06:15–06:28',
    purpose: 'Add two connective phrases matching the product’s “building blocks” thesis.',
    type: 'block-intro',
    eyebrow: 'TWO RIDICULOUSLY USEFUL PHRASES',
    blocks: [
      { id: 'claro', pt: 'claro', gloss: 'of course' },
      { id: 'porque_nao', pt: 'porque não?', gloss: 'why not?' },
    ],
    tapPrompt: 'Tap each phrase once to hear it.',
    requireAllTaps: true,
    cta: 'CONTINUE',
    reveal: 'No grammar lesson. Just two pieces you will hear and use constantly.',
    introduces: ['claro', 'porque_nao'],
    capture: ['audio_boosters'],
  },
  {
    id: 'S33',
    name: 'Use CLARO / PORQUE NÃO?',
    stage: 'FINAL APPROACH',
    timecode: '06:28–06:43',
    purpose: 'Attach each booster to a social intention.',
    type: 'match',
    context: 'Two replies. Two moods.',
    pairs: [
      { blockId: 'claro', pt: 'Claro.', en: 'Of course.' },
      { blockId: 'porque_nao', pt: 'Porque não?', en: 'Why not?' },
    ],
    swapFeedback: 'One is certainty; one is openness. Claro = of course. Porque não? = why not?',
    reveal: 'Tiny phrases make you sound dramatically more conversational.',
    acquires: ['claro', 'porque_nao'],
  },
  {
    id: 'S34',
    name: 'Maverick check 02',
    stage: 'FINAL APPROACH',
    timecode: '06:43–07:02',
    purpose: 'Retrieve a mixed set after significant interference.',
    type: 'recall-burst',
    checkpoint: 2,
    eyebrow: 'MAVERICK CHECK',
    sub: 'Five. Fast. No scene.',
    cards: [
      { cue: 'I lost…', answer: 'perdi', options: ['perdi', 'nao_vou', 'preciso_de'] },
      { cue: 'I can’t…', answer: 'nao_consigo', options: ['nao_vou', 'nao_consigo', 'podes'] },
      { cue: 'I’m not going to…', answer: 'nao_vou', options: ['nao_consigo', 'perdi', 'nao_vou'] },
      { cue: 'when', answer: 'quando', options: ['quando', 'o_que_estas_a', 'comigo'] },
      { cue: 'why not?', answer: 'porque_nao', options: ['claro', 'porque_nao', 'quando'] },
    ],
    reveal: 'Good. They’re surviving the journey.',
  },
  {
    id: 'S35',
    name: 'Your Portuguese — 10 pieces',
    stage: 'FINAL APPROACH',
    timecode: '07:02–07:20',
    purpose: 'Create an explicit sense of acquisition immediately before transfer testing.',
    type: 'inventory',
    view: 'inventory_view_final',
    eyebrow: 'YOUR PORTUGUESE',
    caption: '10 pieces. Now prove they work without Maverick.',
    cta: 'LAND IN LISBON',
  },

  // ------------------------------------------------------------------ LISBON
  // No Top Gun wording, aviation motif or film cue from here on (spec §9).
  {
    id: 'L01',
    name: 'Lisbon test — COMIGO',
    stage: 'LISBON',
    timecode: '07:20–07:32',
    purpose: 'Cold transfer of COMIGO.',
    type: 'tiles',
    eyebrow: 'LISBON. NO FILM. NO CLUES.',
    context: 'Your friend gets up to leave the café.',
    headline: '“Come with me.”',
    tiles: [
      { id: 'vem', text: 'Vem' },
      { id: 'comigo', text: 'comigo' },
      { id: 'amanha', text: 'amanhã', distractor: true },
    ],
    answer: ['vem', 'comigo'],
    hint1: 'You learned “with me” first. Find that piece.',
    chipHint: 'comigo',
    reveal: 'That’s yours.',
  },
  {
    id: 'L02',
    name: 'Lisbon test — PRECISO DE',
    stage: 'LISBON',
    timecode: '07:32–07:44',
    purpose: 'Cold transfer of need construction.',
    type: 'tiles',
    context: 'You sit down for lunch.',
    headline: '“I need water.”',
    tiles: [
      { id: 'preciso', text: 'Preciso' },
      { id: 'de', text: 'de' },
      { id: 'agua', text: 'água' },
    ],
    answer: ['preciso', 'de', 'agua'],
    hint1: 'Keep your “I need…” block together.',
    chipHint: 'preciso_de',
    reveal: 'Good.',
  },
  {
    id: 'L03',
    name: 'Lisbon test — NÃO CONSIGO',
    stage: 'LISBON',
    timecode: '07:44–07:56',
    purpose: 'Cold transfer of conversational repair.',
    type: 'tiles',
    context: 'Someone is speaking much too quickly.',
    headline: '“I can’t understand.”',
    tiles: [
      { id: 'nao_consigo', text: 'Não consigo' },
      { id: 'perceber', text: 'perceber' },
      { id: 'consigo', text: 'consigo', distractor: true },
    ],
    answer: ['nao_consigo', 'perceber'],
    hint1: 'Start with your “I can’t…” block.',
    chipHint: 'nao_consigo',
    reveal: 'Exactly.',
  },
  {
    id: 'L04',
    name: 'Lisbon test — PERDI',
    stage: 'LISBON',
    timecode: '07:56–08:08',
    purpose: 'Cold transfer of a simple past event.',
    type: 'choice',
    context: 'You pat every pocket.',
    headline: '“I lost my keys.”',
    options: [
      { id: 'perdi_as_chaves', pt: 'Perdi as chaves.', correct: true },
      { id: 'perdeu_as_chaves', pt: 'Perdeu as chaves.', feedback: 'That means he/she lost. You’re speaking about yourself.' },
      { id: 'preciso_das_chaves', pt: 'Preciso das chaves.', feedback: 'That says you need the keys. You need your “I lost…” block.' },
    ],
    chipHint: 'perdi',
    reveal: 'Perdi. You remembered it.',
  },
  {
    id: 'L05',
    name: 'Lisbon test — O QUE ESTÁS A…?',
    stage: 'LISBON',
    timecode: '08:08–08:22',
    purpose: 'Cold transfer of the pt-PT progressive question pattern.',
    type: 'tiles',
    context: 'A friend arrives with a bright green drink.',
    headline: '“What are you drinking?”',
    tiles: [
      { id: 'o_que', text: 'O que' },
      { id: 'estas_a', text: 'estás a' },
      { id: 'beber', text: 'beber' },
      { id: 'q', text: '?' },
      { id: 'estas', text: 'estás', distractor: true },
    ],
    answer: ['o_que', 'estas_a', 'beber', 'q'],
    rules: [
      { when: 'uses', tile: 'estas', message: 'Portugal pattern: estás a + verb.' },
    ],
    chipHint: 'o_que_estas_a',
    reveal: 'Perfect Portuguese for Portugal.',
  },
  {
    id: 'L06',
    name: 'Lisbon test — QUANDO',
    stage: 'LISBON',
    timecode: '08:22–08:34',
    purpose: 'Cold discrimination of WHEN.',
    type: 'choice',
    context: 'You’re making plans for later.',
    headline: '“When are you going?”',
    options: [
      { id: 'quando_vais', pt: 'Quando vais?', correct: true },
      { id: 'onde_vais', pt: 'Onde vais?', feedback: 'That asks where, not when.' },
      { id: 'podes_ir', pt: 'Podes ir?', feedback: 'That asks whether someone can go.' },
    ],
    chipHint: 'quando',
    reveal: 'Quando. Banked and retrieved.',
  },
  {
    id: 'L07',
    name: 'Lisbon test — PORQUE NÃO?',
    stage: 'LISBON',
    timecode: '08:34–08:45',
    purpose: 'Cold recall of a conversational booster.',
    type: 'choice',
    context: '“Another coffee?” You’re persuadable.',
    headline: '“Why not?”',
    options: [
      { id: 'porque_nao', pt: 'Porque não?', correct: true },
      { id: 'claro', pt: 'Claro.', feedback: 'Also a perfectly good reply to the offer — but the prompt asks specifically for “Why not?”' },
      { id: 'quando', pt: 'Quando?', feedback: 'Quando = when.' },
    ],
    chipHint: 'porque_nao',
    reveal: 'Porque não?',
  },
  {
    id: 'L08',
    name: 'Lisbon test — PODES',
    stage: 'LISBON',
    timecode: '08:45–08:58',
    purpose: 'Finish with a phrase the learner could genuinely use in their next Portuguese conversation.',
    type: 'tiles',
    context: 'You missed what the waiter said.',
    headline: '“Can you repeat?”',
    note: 'repetir = repeat',
    tiles: [
      { id: 'podes', text: 'Podes' },
      { id: 'repetir', text: 'repetir' },
      { id: 'q', text: '?' },
    ],
    answer: ['podes', 'repetir', 'q'],
    hint1: 'Start with “Can you…?”',
    chipHint: 'podes',
    reveal: 'Podes repetir? That one is worth keeping.',
  },
  {
    id: 'L09',
    name: 'Transfer result',
    stage: 'LISBON',
    timecode: '08:58–09:12',
    purpose: 'Turn performance into evidence of genuine acquisition, not game points.',
    type: 'result',
    headline: 'THE FILM DISAPPEARED. THE LANGUAGE DIDN’T.',
    cta: 'SHOW ME WHAT I CAN SAY',
    lowScoreCopy:
      'Some are yours already. Some need one more encounter. That is exactly what recall is for.',
  },
  {
    id: 'L10',
    name: 'Generativity reveal',
    stage: 'LISBON',
    timecode: '09:12–09:26',
    purpose: 'Demonstrate that the learner acquired combinable language, not isolated quotes.',
    type: 'generativity',
    headline: 'LOOK WHAT 10 PIECES CAN DO.',
    lines: [
      { pt: 'Podes vir comigo?', en: 'Can you come with me?' },
      { pt: 'Não consigo perceber.', en: 'I can’t understand.' },
      { pt: 'Preciso de água.', en: 'I need water.' },
      { pt: 'Quando vais?', en: 'When are you going?' },
      { pt: 'Porque não?', en: 'Why not?' },
    ],
    closing: 'Top Gun was the scaffolding. You can take the language with you.',
    cta: 'CONTINUE',
  },
  {
    id: 'L11',
    name: 'Reveal the platform',
    stage: 'LISBON',
    timecode: '09:26–09:42',
    purpose: 'Test whether the learner understands and wants the broader “culture becomes curriculum” proposition.',
    type: 'preference',
    headline: 'TOP GUN WAS JUST ONE WORLD.',
    sub: 'What would you learn from next?',
    options: [
      { id: 'friends', title: 'FRIENDS', desc: 'everyday conversation' },
      { id: 'james_bond', title: 'JAMES BOND', desc: 'confidence, requests, instructions' },
      { id: 'football', title: 'FOOTBALL', desc: 'opinions, reactions, arguments' },
      { id: 'songs', title: 'SONGS YOU KNOW BY HEART', desc: 'phrases and rhythm' },
      { id: 'books', title: 'BOOKS & STORIES', desc: 'language through narrative' },
    ],
    reveal: 'That choice is the beginning of your curriculum.',
    cta: 'CONTINUE',
  },
  {
    id: 'L12',
    name: 'Continuation intent',
    stage: 'LISBON',
    timecode: '09:42–10:00',
    purpose: 'Capture the most important product-desire metric.',
    type: 'continuation',
    context: 'One last question.',
    headline: 'Would you do another 10 minutes right now?',
    options: [
      { id: 'yes', label: 'YES, GIVE ME ANOTHER', reply: 'Good. That’s what we wanted to know.' },
      { id: 'maybe', label: 'MAYBE LATER', reply: 'Useful. What would make you come back?' },
      { id: 'no', label: 'NOT FOR ME', reply: 'Even more useful. Tell us what didn’t work.' },
    ],
    followUp: 'What should we build next?',
  },
]

/** The eight Lisbon items that make up the transfer score. */
export const FINAL_TEST_ITEMS = ['L01', 'L02', 'L03', 'L04', 'L05', 'L06', 'L07', 'L08']

export const MISSION_01: Mission = {
  mission_id: 'mission_01',
  property_id: 'top_gun',
  property_label: 'Top Gun',
  locale: 'pt-PT',
  targets_new: [
    'comigo',
    'podes',
    'preciso_de',
    'nao_consigo',
    'perdi',
    'nao_vou',
    'o_que_estas_a',
    'quando',
    'claro',
    'porque_nao',
  ],
  targets_reinforced: [],
  stages: ['PRE-FLIGHT', 'TAKE-OFF', 'CRUISE', 'FINAL APPROACH', 'LISBON'],
  screens: SCREENS,
  transfer_items: FINAL_TEST_ITEMS,
}
