/**
 * THE WALK — what gets pointed at, in what order, and what is said about it.
 *
 * Sam: "Build a Club intro animation that walks through each icon in the bottom, mid and
 * top rails and the Logo tap which will take you to the Club home page not app home page."
 *
 * Three rails and a logo, and the ORDER is bottom, mid, top — his order, and it is the
 * right one for a reason he did not have to state. The bottom rail is the only thing on
 * this phone that is on every screen, so it is where somebody who is lost goes first; the
 * boards are what Yours is FOR; the top rail is the two things that are about you rather
 * than about the product. The logo is last because it is the way back to the room they
 * were just welcomed into, which is the sentence the walk should end on.
 *
 * EVERY TARGET IS A data-testid THAT ALREADY EXISTS, and scripts/walk-check.mts asserts it
 * in a browser rather than trusting this comment. A step pointing at a control that was
 * renamed is a circle drawn over empty sand, and it is invisible in the DOM — which is the
 * exact class of fault that has shipped here before.
 *
 * `opens` IS THREE WORDS; `shot` IS A PICTURE, and both exist because the screen has two
 * jobs now.
 *
 * The first build had no screenshots, on the argument that a picture of DUB inside DUB goes
 * stale the first time either screen is touched — which is true, and is why most steps
 * still carry three words rather than an image. Sam then named the second job: "It does
 * need to show a screenshot of the Vibes selector and the Top Gun Talk to me Goose walk
 * through for us to be able to put it on the main home page (and maybe we use it as an ad
 * in future)."
 *
 * That changes the calculation rather than refuting it. A tutorial can say "what is on"
 * and be understood by somebody already holding the phone. An advert is shown to somebody
 * who has never seen the product, and three words is not a reason to download anything —
 * the picture IS the claim. So two steps carry one, and they are the two that show what
 * DUB actually does: a shelf of films and songs you already know, and a line from Top Gun
 * coming apart into three sentences you can use.
 *
 * STALENESS IS HANDLED RATHER THAN AVOIDED. scripts/shots.mts regenerates both from the
 * live product at 390x844, so they are rebuilt the same way every other generated asset is,
 * and walk-check asserts the files exist. A screenshot nobody can regenerate is the thing
 * that rots; one with a command next to it is a build artefact.
 *
 * `say` IS ONE SENTENCE AND IT NAMES THE CONTROL'S JOB, never its appearance. "The house is
 * the Club" teaches nothing — somebody can see it is a house. What they cannot see is that
 * it is where the city lives.
 */
export interface WalkStep {
  /** For analytics, and for the check to name a failing step. */
  id: string
  /**
   * The data-testid of the real control. Measured at runtime — never a coordinate.
   *
   * Empty on a step that points at nothing — see `pick`. Every other step in this file
   * names a control that is on the screen, and the walk filters out any whose control is
   * absent, which is why this cannot simply be optional: a step with no target would be
   * dropped by that filter on the way in.
   */
  target: string
  /**
   * A STEP THAT ASKS SOMETHING INSTEAD OF POINTING AT SOMETHING.
   *
   * Sam: "add the pick your mentor concept to the walk through and have some fun with it."
   *
   * Every other step here is a caption over a hole: this is where FIND is, this is what
   * the cog does. This one has no hole and no control, because the thing it is about does
   * not exist on the screen yet — it is a choice, and making it is what brings it into
   * existence.
   *
   * WHY IT GOES IN THE WALK AT ALL. A "tone of voice" dropdown in Settings is a
   * preference, and nobody has ever changed one. Choosing the person who is going to talk
   * to you is a character choice, it happens once, and the walk is the only place DUB
   * introduces itself — so it is the one moment where asking is natural rather than
   * administrative.
   *
   * It is also the only step somebody can get WRONG, which is why it cannot be a hole: a
   * circle around part of the page while the caption asks a question would be two
   * instructions at once.
   */
  pick?: 'mentor'
  /** The caption. Big, white, low on the screen. */
  say: string
  /** What is behind it, when saying so helps. Three or fewer: this is a label, not a menu. */
  opens?: string[]
  /*
    A PICTURE OF THE THING ITSELF, on the two steps that have to work for a stranger.

    Only where the screen is the argument — see the note above. Everything else is a
    control somebody is looking at while the overlay describes it, and a photograph of a
    control you can already see is noise.

    Regenerated by `npm run shots` from the live product, never hand-cropped.
  */
  shot?: { src: string; alt: string }
  /** The last step's button, when 'GOT IT' is not the right words. */
  done?: string
  /**
   * A SECOND LINE, UNDER THE CAPTION, on the steps that are making an argument.
   *
   * Sam: "it is too oblique at the moment and needs to lock into the proposition above
   * the process."
   *
   * The furniture steps need one sentence each — a tab is a tab. The steps that say what
   * DUB is FOR need two: the claim, and the thing that makes it true. Without this the
   * opening step would have to be one long sentence, which at display size is a paragraph
   * on a photograph.
   */
  more?: string
}

export const WALK: WalkStep[] = [
  /*
    WHAT DUB IS, BEFORE WHERE ANYTHING IS.

    Sam: "it is too oblique at the moment and needs to lock into the proposition above the
    process."

    He is right and the fault was structural rather than a wording problem. Every step
    here named a control — FIND is for this, the cog is that, your boards are these —
    which is a tour of the furniture. Somebody finished it knowing where the buttons were
    and not what the product was FOR, and a walk-through that has to be followed by an
    explanation has not worked.

    So the first three steps make the argument and the rest show the rooms. They point at
    nothing, like the mentor picker, because what they are about is not on the screen: it
    is the reason the screen exists.

    THE ORDER IS THE PITCH SAM GIVES OUT LOUD. The correction first — everybody teaches
    you the wrong Portuguese — then what DUB does instead, then the thing that makes it
    worth doing, which is other people. Process after that.
  */
  {
    id: 'why',
    target: '',
    say: 'Every big app teaches you Brazilian Portuguese. You live in Lisbon.',
    more: 'DUB teaches the one they actually speak here — estás, telemóvel, uma bica.',
  },
  {
    id: 'legend',
    target: '',
    say: 'So it starts with you. Not a pencil, not a train timetable.',
    more:
      'Thirteen questions about who you are, said out loud. Ten minutes, and you can introduce yourself to anybody.',
    shot: {
      src: '/walk/legend.png',
      alt: 'The first Legend question — Como te chamas? — with a microphone under it and Say it out loud.',
    },
  },
  {
    id: 'table',
    target: '',
    /*
      THE THIRD CLAIM, AND THE ONE THAT NAMES THE ACTUAL PROBLEM.

      Sam, twice and more bluntly the second time: "ex-pats hang out together and never
      feel a pressing need to learn the new language", and then — "ex-pats are lazy, they
      defer to speaking their native language with compatriots. This is about getting
      people out of their comfort zone and actually trying to speak the language."

      So this step does not say "then you use it on somebody", which was the first draft
      and is a pleasantry. It says the thing is HARD, because the person watching already
      knows it is and a product that pretends otherwise has lost them. "That is the hard
      part" is the sentence somebody nods at.

      AND THE RELIEF HAS TO ARRIVE IN THE SAME BREATH. Naming the discomfort without
      resolving it is just a warning. "Everybody there is as uncomfortable as you" is the
      whole mechanic — it is why a table works where a resolution to try harder does not,
      and it is the one thing no other app can say, because no other app knows what
      anybody at the table can actually do.
    */
    say: 'Then you have to actually use it. That is the hard part.',
    more:
      'A table is six people who can already say the same things, and the first ten minutes are in Portuguese. Everybody there is as uncomfortable as you, which is what makes it possible.',
    shot: {
      src: '/walk/table.png',
      alt: 'The table screen — two people at a pavement table in Lisbon at dusk, with the rule under it.',
    },
  },
  /*
    AND NOW THE ROOMS.

    THE BOTTOM RAIL, four tabs, and each one gets its own step rather than one step for
    the bar.

    A single circle around the whole bar would be the honest shape of "this is always
    here" and it would teach nothing: four tabs is four decisions, and the only useful
    thing to say about a tab is what is behind it. See components/BottomNav.tsx, whose own
    note argues the four are "a claim about what those things ARE rather than a way of
    saving space" — so the walk makes the same claim out loud.
  */
  {
    id: 'tab-find',
    target: 'tab-find',
    /*
      FIND IS WHERE YOU BROWSE, which is the job the tab actually does now.

      It said "The Club is your city in Portuguese", which described the whole product
      while pointing at one scrolling feed — the confusion the rename exists to end. The
      Club is everything after the Legend; this tab is the part of it you open with nothing
      particular in mind.
    */
    say: 'FIND is for when you have no plan — rooms, nights out and the words for them.',
    opens: ['What is on', 'Rooms', 'Drops'],
  },
  {
    id: 'tab-yours',
    target: 'tab-yours',
    say: 'YOURS is this screen — everything you have built, and the only one that is about you.',
  },

  /*
    THE MID RAIL. Four boards and a MORE, and they are pointed at as ONE step rather than
    five.

    This is where the walk stops being a tour of controls and starts being a tour of the
    product, and the difference matters: the four tabs go to four different places, so
    four steps is four facts. The boards all do the same thing — they change the grid
    under them — so five steps would be the same sentence five times with a different
    noun, which is how a walk-through becomes something people skip.

    The hole lands on the RAIL rather than on the library card — `collection` is the card
    around the whole thing and is 900px tall, so a circle at its centre lands on a grid
    tile, which is the opposite of what this step says. See the note on `rail` in
    components/Collection.tsx.
  */
  {
    id: 'boards',
    target: 'rail',
    say: 'Your boards. Tap one to change what is in the grid — and MORE has six more.',
    opens: ['Legend', 'Vibes', 'Cheats', 'Drops'],
    /*
      THE SHELF, because VIBES is the word the whole product turns on and it means nothing
      from outside.

      Sam, on putting this on the home page: "It does need to show a screenshot of the Vibes
      selector." A stranger reading "Vibes" learns nothing; a stranger seeing Top Gun,
      Bridget Jones and James Bond on a shelf understands the entire proposition in a
      second. This is the picture that does that.
    */
    shot: {
      src: '/walk/vibes.png',
      alt: 'The DUB vibe shelf: Top Gun, Bridget Jones, James Bond and the rest, each a card you can open.',
    },
  },
  /*
    AND THE LEGEND ON ITS OWN, because it is not a peer of the other three.

    Collection.tsx: "THE LEGEND IS THE DEFAULT, always... It is about the Legend, and the
    first card on it is the one that practises it." A board that is the default and holds
    the thing the whole product is for has earned a sentence of its own, and this is the
    one step of the six that is about what to DO rather than where something is.
  */
  {
    id: 'rail-legend',
    target: 'rail-legend',
    say: 'Your Legend lives here. Practise it cold, and add to it as you learn.',
    /*
      AND WHAT A VIBE ACTUALLY DOES TO A LINE, which is the demonstration nothing else here
      can make in words.

      Sam: "and the Top Gun Talk to me Goose walk through." It is the strongest argument the
      product has — you already half-know this, here is the Portuguese, and `comigo` comes
      out of it into three sentences you would genuinely say. Said as a sentence it is a
      claim; shown as the card it is a proof, which is the difference between a tutorial and
      an advert.
    */
    shot: {
      src: '/walk/goose.png',
      alt: 'Talk to me, Goose — Fala comigo, Goose — with comigo unpacking into Vem comigo, Fica comigo and Podes vir comigo?',
    },
  },

  /*
    THE TOP RAIL — the two controls on Yours that are about this person rather than about
    the product. Both are on the identity row rather than in a bar of their own, which is
    Profile.tsx's own decision and the reason a walk is worth having: they are small, they
    are high, and nothing else on the screen looks like them.
  */
  {
    id: 'inbox-door',
    target: 'inbox-door',
    say: 'The inbox. The red number is what has landed since you last looked.',
    opens: ['Drops near you', 'What is new'],
  },

  /*
    THE LOGO, LAST, AND THE CAPTION PROMISES THE CLUB.

    Sam: "the Logo tap which will take you to the Club home page not app home page." Where
    the mark actually points is HIS fix and not this walk's — so the caption describes the
    destination he has named, and components/Walkthrough.tsx sends the last button to
    /club rather than touching the mark's own routing. If the two ever disagree it is
    because the fix has not landed, which is a visible disagreement rather than a silent
    one.
  */
  /*
    AND THE THING THAT IS WATCHING, which is the step that says there is somewhere to get to.

    Sam: "build that into the walk-through so people get the idea there is progress to be
    made." Every other step here names a place; this one names a relationship, and it is the
    only step that answers "why would I keep doing this".

    Said in the voice the whole feature is written in — Sam's brief for it was "the coolest
    and best teacher you ever had, like being taught by your elder brother's best mate who is
    really cool" — so it is flat and specific rather than encouraging. "I notice" rather than
    "DUB tracks your progress", which is the same sentence wearing a lanyard.

    Second to last, before the mark. The walk ends on the way back into the Club, and the
    reason to go back is this.
  */
  /*
    AND THE TABLE ITSELF, pointed at on the screen rather than only claimed at the start.

    The third step makes the argument; this one shows where it lives. Before NOTICED,
    because a reason to speak to a person beats a report on how your speaking is going —
    which is the same order the Yours screen itself uses.
  */
  {
    id: 'table-door',
    target: 'yours-table',
    say: 'And this is where you find one. Six seats, a real bar, a real night.',
    opens: ['Who is coming', 'What they can say'],
  },
  {
    id: 'noticed',
    target: 'yours-noticed',
    say: 'I notice what you can say and what keeps slipping. That is how this gets better.',
    opens: ['What landed', 'What is close'],
  },
  /*
    AND THEN: WHO SAYS IT.

    Straight after NOTICED, which is the step that introduces the watching — so the order
    is "something is paying attention to you", then "pick who it sounds like". Reversed,
    the question is about nobody.

    The caption is a question rather than a statement, which is the only one in this file,
    because this is the only step that wants an answer rather than a nod.
  */
  {
    id: 'mentor',
    /*
      NOTHING TO POINT AT. The target is empty on purpose — the choice is not a control on
      Yours, it is a thing being asked. The walk's own filter keeps a step whose target is
      empty, precisely so this one survives on a screen where nothing else would.
    */
    target: '',
    pick: 'mentor',
    say: 'One last thing. Who do you want telling you how it is going?',
  },
  {
    id: 'logo',
    target: 'yours-wordmark',
    say: 'And the mark, anywhere you see it, is the way back to the Club.',
    done: 'TAKE ME IN',
  },
]
