/**
 * THE WALK — what gets pointed at, in what order, and what is said about it.
 *
 * Sam: "Build a Club intro animation that walks through each icon in the bottom, mid and
 * top rails and the Logo tap which will take you to the Club home page not app home page."
 *
 * Three rails and a logo, and the ORDER is bottom, mid, top — his order, and it is the
 * right one for a reason he did not have to state. The bottom rail is the only thing on
 * this phone that is on every screen, so it is where somebody who is lost goes first; the
 * boards are what Yours is FOR; the top rail is the two things that are about you rather
 * than about the product. The logo is last because it is the way back to the room they
 * were just welcomed into, which is the sentence the walk should end on.
 *
 * EVERY TARGET IS A data-testid THAT ALREADY EXISTS, and scripts/walk-check.mts asserts it
 * in a browser rather than trusting this comment. A step pointing at a control that was
 * renamed is a circle drawn over empty sand, and it is invisible in the DOM — which is the
 * exact class of fault that has shipped here before.
 *
 * `opens` IS THREE WORDS; `shot` IS A PICTURE, and both exist because the screen has two
 * jobs now.
 *
 * The first build had no screenshots, on the argument that a picture of DUB inside DUB goes
 * stale the first time either screen is touched — which is true, and is why most steps
 * still carry three words rather than an image. Sam then named the second job: "It does
 * need to show a screenshot of the Vibes selector and the Top Gun Talk to me Goose walk
 * through for us to be able to put it on the main home page (and maybe we use it as an ad
 * in future)."
 *
 * That changes the calculation rather than refuting it. A tutorial can say "what is on"
 * and be understood by somebody already holding the phone. An advert is shown to somebody
 * who has never seen the product, and three words is not a reason to download anything —
 * the picture IS the claim. So two steps carry one, and they are the two that show what
 * DUB actually does: a shelf of films and songs you already know, and a line from Top Gun
 * coming apart into three sentences you can use.
 *
 * STALENESS IS HANDLED RATHER THAN AVOIDED. scripts/shots.mts regenerates both from the
 * live product at 390x844, so they are rebuilt the same way every other generated asset is,
 * and walk-check asserts the files exist. A screenshot nobody can regenerate is the thing
 * that rots; one with a command next to it is a build artefact.
 *
 * `say` IS ONE SENTENCE AND IT NAMES THE CONTROL'S JOB, never its appearance. "The house is
 * the Club" teaches nothing — somebody can see it is a house. What they cannot see is that
 * it is where the city lives.
 */
export interface WalkStep {
  /** For analytics, and for the check to name a failing step. */
  id: string
  /** The data-testid of the real control. Measured at runtime — never a coordinate. */
  target: string
  /** The caption. Big, white, low on the screen. */
  say: string
  /** What is behind it, when saying so helps. Three or fewer: this is a label, not a menu. */
  opens?: string[]
  /*
    A PICTURE OF THE THING ITSELF, on the two steps that have to work for a stranger.

    Only where the screen is the argument — see the note above. Everything else is a
    control somebody is looking at while the overlay describes it, and a photograph of a
    control you can already see is noise.

    Regenerated by `npm run shots` from the live product, never hand-cropped.
  */
  shot?: { src: string; alt: string }
  /** The last step's button, when 'GOT IT' is not the right words. */
  done?: string
}

export const WALK: WalkStep[] = [
  /*
    THE BOTTOM RAIL, four tabs, and each one gets its own step rather than one step for
    the bar.

    A single circle around the whole bar would be the honest shape of "this is always
    here" and it would teach nothing: four tabs is four decisions, and the only useful
    thing to say about a tab is what is behind it. See components/BottomNav.tsx, whose own
    note argues the four are "a claim about what those things ARE rather than a way of
    saving space" — so the walk makes the same claim out loud.
  */
  {
    id: 'tab-find',
    target: 'tab-find',
    /*
      FIND IS WHERE YOU BROWSE, which is the job the tab actually does now.

      It said "The Club is your city in Portuguese", which described the whole product
      while pointing at one scrolling feed — the confusion the rename exists to end. The
      Club is everything after the Legend; this tab is the part of it you open with nothing
      particular in mind.
    */
    say: 'FIND is for when you have no plan — rooms, nights out and the words for them.',
    opens: ['What is on', 'Rooms', 'Drops'],
  },
  {
    id: 'tab-on',
    target: 'tab-on',
    say: 'ON is the calendar. Real nights out, with the Portuguese you will need at them.',
    opens: ['This week', 'Gigs', 'Save to your phone'],
  },
  {
    /*
      ASK is the one tab that is not a place — BottomNav says so in its own comment — and
      the caption has to say that, because a person who taps it expecting a screen and
      gets a panel over the one they were on has learnt that the bar is unreliable.
    */
    id: 'tab-ask',
    target: 'tab-ask',
    say: 'ASK opens on top of whatever you are doing. Say it in English, get it in Portuguese.',
  },
  {
    id: 'tab-yours',
    target: 'tab-yours',
    say: 'YOURS is this screen — everything you have built, and the only one that is about you.',
  },

  /*
    THE MID RAIL. Four boards and a MORE, and they are pointed at as ONE step rather than
    five.

    This is where the walk stops being a tour of controls and starts being a tour of the
    product, and the difference matters: the four tabs go to four different places, so
    four steps is four facts. The boards all do the same thing — they change the grid
    under them — so five steps would be the same sentence five times with a different
    noun, which is how a walk-through becomes something people skip.

    The hole lands on the RAIL rather than on the library card — `collection` is the card
    around the whole thing and is 900px tall, so a circle at its centre lands on a grid
    tile, which is the opposite of what this step says. See the note on `rail` in
    components/Collection.tsx.
  */
  {
    id: 'boards',
    target: 'rail',
    say: 'Your boards. Tap one to change what is in the grid — and MORE has six more.',
    opens: ['Legend', 'Vibes', 'Cheats', 'Drops'],
    /*
      THE SHELF, because VIBES is the word the whole product turns on and it means nothing
      from outside.

      Sam, on putting this on the home page: "It does need to show a screenshot of the Vibes
      selector." A stranger reading "Vibes" learns nothing; a stranger seeing Top Gun,
      Bridget Jones and James Bond on a shelf understands the entire proposition in a
      second. This is the picture that does that.
    */
    shot: {
      src: '/walk/vibes.png',
      alt: 'The DUB vibe shelf: Top Gun, Bridget Jones, James Bond and the rest, each a card you can open.',
    },
  },
  /*
    AND THE LEGEND ON ITS OWN, because it is not a peer of the other three.

    Collection.tsx: "THE LEGEND IS THE DEFAULT, always... It is about the Legend, and the
    first card on it is the one that practises it." A board that is the default and holds
    the thing the whole product is for has earned a sentence of its own, and this is the
    one step of the six that is about what to DO rather than where something is.
  */
  {
    id: 'rail-legend',
    target: 'rail-legend',
    say: 'Your Legend lives here. Practise it cold, and add to it as you learn.',
    /*
      AND WHAT A VIBE ACTUALLY DOES TO A LINE, which is the demonstration nothing else here
      can make in words.

      Sam: "and the Top Gun Talk to me Goose walk through." It is the strongest argument the
      product has — you already half-know this, here is the Portuguese, and `comigo` comes
      out of it into three sentences you would genuinely say. Said as a sentence it is a
      claim; shown as the card it is a proof, which is the difference between a tutorial and
      an advert.
    */
    shot: {
      src: '/walk/goose.png',
      alt: 'Talk to me, Goose — Fala comigo, Goose — with comigo unpacking into Vem comigo, Fica comigo and Podes vir comigo?',
    },
  },

  /*
    THE TOP RAIL — the two controls on Yours that are about this person rather than about
    the product. Both are on the identity row rather than in a bar of their own, which is
    Profile.tsx's own decision and the reason a walk is worth having: they are small, they
    are high, and nothing else on the screen looks like them.
  */
  {
    id: 'inbox-door',
    target: 'inbox-door',
    say: 'The inbox. The red number is what has landed since you last looked.',
    opens: ['Drops near you', 'What is new'],
  },
  {
    id: 'yours-settings',
    target: 'yours-settings',
    say: 'The cog is settings — your account, your language, and what the app may send you.',
  },

  /*
    THE LOGO, LAST, AND THE CAPTION PROMISES THE CLUB.

    Sam: "the Logo tap which will take you to the Club home page not app home page." Where
    the mark actually points is HIS fix and not this walk's — so the caption describes the
    destination he has named, and components/Walkthrough.tsx sends the last button to
    /club rather than touching the mark's own routing. If the two ever disagree it is
    because the fix has not landed, which is a visible disagreement rather than a silent
    one.
  */
  {
    id: 'logo',
    target: 'yours-wordmark',
    say: 'And the mark, anywhere you see it, is the way back to the Club.',
    done: 'TAKE ME IN',
  },
]
