/**
 * The wordmarks, from the files to the code.
 *
 *   npm run brand
 *
 * Two consumers want the same mark in incompatible shapes. The app inlines it so that
 * `currentColor` works — the header is blue and needs a white mark, which an <img> can
 * never do. next/og resolves no CSS and no component tree at all, so the share image and
 * the icons need the raw path data as a literal.
 *
 * So public/brand/*.svg is the source of truth a designer edits, and this generates
 * content/marks.ts from it. `npm run lint:content` fails if they have drifted, which is
 * the only thing that stops two copies becoming two marks.
 *
 * It also derives the favicon, which is not supplied and should not be: three letters do
 * not survive 16px. The U is the distinctive glyph — it is the one carrying the
 * speech-bubble tail, which is the whole idea in the mark — so the U's subpath is lifted
 * out and cropped to its own bounds.
 */
import { readFileSync, writeFileSync } from 'node:fs'

function read(file: string): { viewBox: string; d: string } {
  const svg = readFileSync('public/brand/' + file, 'utf8')
  const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1]
  const d = /\bd="([^"]+)"/.exec(svg)?.[1]
  if (!viewBox || !d) throw new Error(file + ' has no viewBox or no path')
  return { viewBox, d }
}

/** Every subpath, with its bounds. The mark is one path with a subpath per glyph. */
function subpaths(d: string): { d: string; x0: number; y0: number; x1: number; y1: number }[] {
  return d
    .split('M ')
    .filter((s) => s.trim())
    .map((s) => {
      const n = (s.match(/-?[0-9.]+/g) ?? []).map(Number)
      const xs = n.filter((_, i) => i % 2 === 0)
      const ys = n.filter((_, i) => i % 2 === 1)
      return {
        d: 'M ' + s.trim(),
        x0: Math.min(...xs),
        y0: Math.min(...ys),
        x1: Math.max(...xs),
        y1: Math.max(...ys),
      }
    })
}

const dub = read('dub.svg')
const club = read('dub-club.svg')

/**
 * The U, found rather than hard-coded.
 *
 * It is the only glyph whose outline drops below the baseline — that IS the tail — so it
 * identifies itself, and a future redraw that moves the letters around cannot silently
 * pick the wrong one.
 */
const glyphs = subpaths(dub.d)
const baseline = Math.max(...glyphs.map((g) => g.y1))
const withTail = glyphs.filter((g) => g.y1 > baseline - 1)
if (withTail.length !== 1) {
  throw new Error(
    'expected exactly one glyph to drop below the baseline (the U and its tail), found ' +
      withTail.length +
      '. If the mark was redrawn, the favicon needs choosing by hand.',
  )
}
const u = withTail[0]
const pad = 8
const mark = {
  viewBox: [u.x0 - pad, u.y0 - pad, u.x1 - u.x0 + pad * 2, u.y1 - u.y0 + pad * 2].join(' '),
  d: u.d,
}

const out = `/**
 * GENERATED by npm run brand. Do not edit — edit public/brand/*.svg and re-run.
 *
 * The path data lives here as well as in the files because the two consumers want
 * incompatible things: the app inlines the mark so currentColor can make it white on a
 * blue header, and next/og resolves no CSS at all so the icons and the share image need
 * a literal. lint:content fails when this file and the SVGs disagree.
 */

export interface Mark {
  viewBox: string
  d: string
  label: string
}

/** The wordmark. */
export const DUB: Mark = {
  viewBox: '${dub.viewBox}',
  label: 'DUB',
  d: '${dub.d}',
}

/** The lock-up a recipient is being invited into. */
export const DUB_CLUB: Mark = {
  viewBox: '${club.viewBox}',
  label: 'DUB CLUB',
  d: '${club.d}',
}

/**
 * The U and its speech-bubble tail, cropped to itself.
 *
 * The favicon, the app icon and the Apple icon. Three letters do not survive 16px; this
 * does, and the tail is the part of the mark that means something.
 */
export const DUB_MARK: Mark = {
  viewBox: '${mark.viewBox}',
  label: 'DUB',
  d: '${mark.d}',
}
`
writeFileSync('content/marks.ts', out)

writeFileSync(
  'public/brand/dub-mark.svg',
  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="' +
    mark.viewBox +
    '" role="img" aria-label="DUB">\n  <path d="' +
    mark.d +
    '" fill="currentColor" fill-rule="evenodd"/>\n</svg>\n',
)

console.log('wordmark   ' + dub.viewBox)
console.log('lock-up    ' + club.viewBox)
console.log('the mark   ' + mark.viewBox + '  (the U, ' + Math.round(u.y1 - baseline + (u.y1 - u.y0)) + ' units tall with its tail)')
console.log('\nwritten: content/marks.ts, public/brand/dub-mark.svg')
